apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apiv2-deployment
  namespace: apiv2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: deployments
  source:
    path: deployments/apiv2/manifests/overlays/test
    repoURL: https://github.com/CuriBio/k8s_curi.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
