kind: Deployment
apiVersion: apps/v1
metadata:
  name: pulse3d
  namespace: pulse3d
  labels:
    app: pulse3d
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: pulse3d
  template:
    metadata:
      labels:
        app: pulse3d
        version: latest
    spec:
      containers:
      - name: pulse3d
        image: 077346344852.dkr.ecr.us-east-2.amazonaws.com/pulse3d_api:0.5.0
        env:
        - name: POSTGRES_USER
          value: curibio_jobs
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: curibio-jobs-creds
              key: curibio_jobs
        - name: POSTGRES_SERVER
          value: psql-rds.default
        - name: POSTGRES_DB
          value: curibio
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: curibio-jwt-secret
              key: jwt-secret
        - name: UPLOADS_BUCKET_ENV
          value: test-pulse3d-uploads
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pulse3d-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
status:
  loadBalancer: {}
spec:
  rules:
  - host: pulse3d.curibio-test.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pulse3d
            port:
              number: 80
