
# based on https://github.com/encode/uvicorn/issues/491#issuecomment-809546591
version: 1
disable_existing_loggers: False
formatters:
  timestamped:
    format: "%(asctime)s %(levelname)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: timestamped
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [console]
