bucket               = "curi-eks-test-cluster-tf-state"
key                  = "test/db-viewer/services/db-viewer.tfstate"
region               = "us-east-2"
dynamodb_table       = ""
workspace_key_prefix = "env"
