apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo
resources:
  - ../../base
  - workflow_defaults.yaml
  #- https://raw.githubusercontent.com/argoproj/argo-workflows/v3.2.9/manifests/namespace-install.yaml
