kind: Deployment
apiVersion: apps/v1
metadata:
  name: apiv2
  labels:
    app: apiv2
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: apiv2
  template:
    metadata:
      labels:
        app: apiv2
        version: latest
    spec:
      nodeSelector:
        group: services
      containers:
        - name: users
          env:
            - name: POSTGRES_USER
              value: curibio_users
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: curibio-users-creds
                  key: curibio_users
            - name: POSTGRES_SERVER
              value: psql-rds.default
            - name: POSTGRES_DB
              value: curibio
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: curibio-jwt-secret
                  key: jwt-secret
            - name: CURIBIO_EMAIL
              valueFrom:
                secretKeyRef:
                  name: curibio-email-creds
                  key: curibio-email
            - name: CURIBIO_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: curibio-email-creds
                  key: curibio-email-password
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
        - name: mantarray
          env:
            - name: CLUSTER_NAME
              value: test
            - name: POSTGRES_USER
              value: curibio_mantarray
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: curibio-mantarray-creds
                  key: curibio_mantarray
            - name: POSTGRES_SERVER
              value: psql-rds.default
            - name: POSTGRES_DB
              value: curibio
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: curibio-jwt-secret
                  key: jwt-secret
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
        - name: event-broker
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: curibio-jwt-secret
                  key: jwt-secret
          imagePullPolicy: Always
          ports:
            - containerPort: 9002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apiv2-ingress
  annotations:
    nginx.org/rewrites: serviceName=mantarray rewrite=/; serviceName=users rewrite=/; serviceName=eventBroker rewrite=/public
status:
  loadBalancer: {}
spec:
  ingressClassName: nginx
  rules:
    - host: apiv2.curibio-test.com
      http:
        paths:
          - path: /users/
            pathType: Prefix
            backend:
              service:
                name: users
                port:
                  number: 80
          - path: /mantarray/
            pathType: Prefix
            backend:
              service:
                name: mantarray
                port:
                  number: 80
          - path: /events/
            pathType: Prefix
            backend:
              service:
                name: eventBroker
                port:
                  number: 80
