apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: advanced-analysis
resources:
  - ../../base
  - advanced-analysis-queue-processor-creds.yaml

patchesStrategicMerge:
  - prod-job-runner.yaml
