minimum_pre_commit_version: 2.11.1
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # Use the ref you want to point at
    hooks:
      # black and docformatter don't do this in docstrings (11/1/19)
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.3.0 # pick a git hash / tag to point to
    hooks:
      - id: black
        args: [--line-length=110]
        exclude: .*pheno.*

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        args: [--print-width=110]
        files: .*\.js$

  # - repo: https://github.com/myint/docformatter
  #   rev: v1.4 # pick a git hash / tag to point to
  #   hooks:
  #     - id: docformatter
  #       exclude: (tests*)

  # # Safety/Security Issues
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  #   rev: v1.2.1
  #   hooks:
  #     - id: python-safety-dependencies-check

  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.4
  #   hooks:
  #     - id: bandit
  #       exclude: tests*

  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v3.4.0 # Use the ref you want to point at
  #   hooks:
  #     - id: detect-private-key

  # # Linting
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.981 # pick a git hash / tag to point to
  #   hooks:
  #     - id: mypy
  #       # additional_dependencies: [nptyping==1.4.0]
  #       exclude: (.*/tests/.*)|(.*pheno.*)

  # - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
  #   rev: v1.0.1
  #   hooks:
  #     - id: rst-linter
  #       exclude: docs

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.0 # pick a git hash / tag to point to
    hooks:
      - id: flake8
        exclude: (.*pheno.*)|(.*tests/conftest.*)
        args: [--max-line-length=110, "--ignore=E722,E501,W503", --per-file-ignores=*/__init__.py:F401]

  # - repo: https://github.com/PyCQA/pydocstyle
  #   # black seems to be working on formatting docstrings, but use this for now
  #   rev: 6.0.0 # pick a git hash / tag to point to
  #   hooks:
  #     - id: pydocstyle
  #       args:
  #         # ignore warnings about missing docstrings. pylint takes care of that
  #         # ignore D203 because it's a bug https://github.com/PyCQA/pydocstyle/issues/141
  #         # ignore D407,D408,D409 because they appear to be in conflict with Google style (they relate to underlining?) https://rsmith.home.xs4all.nl/programming/improving-my-python-coding.html
  #         # ignore D406 because it appears to be in conflict with Google style (complains about 'Raises:')
  #         # ignore D413 about final blank line because docformatter gets rid of it
  #         # ignore D213 because mutually exclusive with D212 https://stackoverflow.com/questions/45990301/pep257-d212-and-d213-conflicts
  #         - --ignore=D100,D101,D102,D103,D104,D105,D106,D107,D203,D407,D408,D409,D406,D413,D213

  - repo: https://github.com/NanoSurface-Biomedical/pre-commit-pylint
    rev: "d805cc60bb5290c2f1ca869d5f1d5e2be720f3fa" # pick a git hash / tag to point to
    hooks:
      - id: python-check-no-print-statments
        exclude: .*pheno.*

  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v7.23.0
  #   hooks:
  #     - id: eslint
  #       files: \.js
  #       types: [file]
  #       args: [--fix]
