FROM node:16.17.0

RUN useradd main_user && groupadd main_group
USER main_user:main_group

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install