apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: deployments
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Cluster applications
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployments
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: deployments
  source:
    repoURL: https://github.com/CuriBio/k8s_curi.git
    targetRevision: HEAD
    path: applications/overlays/test
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
