---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: argo
spec:
  encryptedData:
    aws_access_key_id: AgBvCw6hCCqBzZPanGA91CP8l45rkqkEXiuASY/04oiIFt1rO1ODSezcLFzzn64Ol9PKQbbPpRt085INbIHxtd23roippi4OCpQVyj0vV7EBf8bWqCXkZAd3wc+IBC55oA634Pfy0Qrc7OZg3fT4ny5aDx1kqvT8pnO69iJNajAPyOcOLZY0xmlc9bSfnN1M38tyrWzFfFwXdVlzK3Lcv5r3N9jMFpSsmywwk3OI8buxT+uRzyu21yXrvVHMvSPait77pHZuITkSYMIpiX86ZTRJZIJzkOqRCp7oYIPh5dQDAU54i87H3VWfT6w5FDAqf3w2ocrvMySOdnWNX1PoOXluzZxDiMOdj4R42gOVoM9shgLcXYsMDgDr64Ta7eTBQ2djzXBMYJsSw8g9sGQtX/M9N48SjtssLgNTfm8dlIPEDH0QIc981SsIQuJaYjew5mWCEy6htwg3AULsQASQbSXGkTMC2vLpP82+E4YZe8gLMpBB8njgyIG/NewWoZPGJsovGPyqhJXAt9TRjRkVX/kLC8ff4TUUqZiRYAscgKEcLt3h/+o16dQ9wNUl5XwOE9lJ1eaF+Bkv7tF7DNDI18TKH7bxgt6+Ammup4vLh+kuQ9nSQpQIri2MicL0/W3KgGLyv/6jQHKKfE/Jgp0WREZlXrWx44JCdKFw1WIk08u4T/62oO40OzCGw8nRC8URGd3vkgjzGMV+8c4Wq+nWMU0+9h2kpw==
    aws_secret_access_key: AgBe9tYWBw2xMnK0w/FATYAsw63DQTk9FqwPxsialcG6syBQJkqT/fJxgOo3Di6Uyw+t1l+uQz8LBNrftqPH0QTxdVEnwyr4YvHELmLbNPprAEn2XQocyXEwcH4aDTTUoBDkCHDSVLjO9O+A6m9ref9EGd/bX/UlUsQhENbCEHzXnAFU/yY3G1ONjtfPcDNscjwZq93vKO/UbrlANwCESZua4NJxFfNJvXBipRmwgpLFeU5q/WfrZ8AT7q3xEUiICmPGuav3zPWlQv7geYk+4L9kCCBKAwFJiF36MwIATHWBVhzMz1afNexc7VvJdW5xuQv0ThGtJc75EuTzEJFAikt5Ld7J6GO9WeQperY6u0gbogGVDRSHbwB1zWkBvDS+wjYqBt8cEm8xxyaW6MRBcZDMTxc3+ErPT3SzYx3+3MPLle/BJBrc0SVYyOokfvqJivfPXAZmxa50vTisaSCSGIc4o9KbIG+J4riPPpj159+lxef3sgJB31+HzKoA8ceNoJ1PvLLv8RP/Nuxf8IBGGub0SQU+jirlxQHeanzQLNJac279ax4XPgznEEIHAeWeXVJ5LabZW7SBwvvLcjGNWAhT95qU228ix22EDzY+CpxkCrX4fWJ8ueMvIVa9W3fiSj55ahl/SwizRNsXHBlGYe1bAdlvmBg7VGfGu+JekC4O9CTMN8H9dbw4c91m8GYVAseyRmMBmS/taU40db0mo9Ow64yfkulb00/xQlC33cK6gA8Mq4J1T6pS
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: argo
