apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access-token
  namespace: argo
spec:
  encryptedData:
    token: AgCT2rIx8HM+91y9nrJgTZxkeSFq1tffMw9TtqrksbbSleZxQb5N+ZMNfCi1DJVeOev09iIqI47M/7tCZIPFRg4lUW6xIQ5vXWqwGRF8wRB9T99NHgnD9x8K+v7Hld4qGkX0Dxb4jnJ9RyAV3LBaE+2pYWtgWq2I9MAb+4jf3dnCadFDxs1uCNDto3j/goGtz992RIyg+Ue1Z2F+/SG5E3+GwikzS6kqVKCr5FGiW6poYbpFvnBfFX1g8M5rZ6NdgWSjr0x1IPlUJQVl8Ff9G4jYiYMZQyzSoHhcN9WH0tYd4CIgIin3lrMOCA+9Qoiluwt0D84Cdl8QjPKngQYNfuEGeRmp0VMhs2Jc6Wdiqsf2wIsYbVK5KIfF1bLjNdEmpEEn+g21WX4ksFC854u6a2wYLkGT+Q+dIIZnKYhCF455HtMqSGyPEgZvgkCCiBn9xFnURSV86RcG5mdfCc5pT+ap2hKaO183aOLg7LL5XNedBXOpHPEI642XZNo7N4wKw862y+Tm8nYc3afWinlu0FNmfxUHiiUquhmSnr1hVDmqtvpf1Pxf3CwjVR6wWCgCQ7DzIXrolyne9s6cSdYxc2UV5BnOoOfjaZbd40XHhled5HZn+sg67lMQHyw/nO3KQPIOnPzAFxjns8okcW0Z7SEIsb1MLiBdNnDbapFTspo0rdjzJFhBg8NItejz8KZ78n94hr9vtLp6czNAPp5qTEzYQPxzewJ9w9N6cVxsj7VUKDsyzjT4fgFT
  template:
    metadata:
      creationTimestamp: null
      name: github-access-token
      namespace: argo

