apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret
  namespace: argo
spec:
  encryptedData:
    token: AgDht++/HeIgKkLW9XiszY/9EhXgqmRCZFjuUoCXpBIiZGv1E2nGidYw+weofD+UxMBGNKugVSKfH3YdhH+0vxtETFZu/tloV3d0uboN7aXZOYYPFc2NCZlKYxIU2shvziuSOLqSobtHXMiIBbF7Li0hQ+C+MvoH4pf21uFtD3wAC0OdHsXX3Rokvf1UxqxnDawmnB87z0MJbEiwW+IBsrEeP0SMThcGNLXarUxnF8W8bAkma3JnxXcCDR7IN3SFbFb7W3U9VHEjGxFYeBLp8Ue43Pws8sQ6vjX7aUF6Iffp3XBuH9agON6a5cPRLKbR+m3w1FjXYEQJjssDNYkx8PXMGqA9IlqyoIh7Gt7fW2s3Ed1QI9460+gRK+ERGY3UfHBBwoIcdSMQrJ7t5J6I3Hii2VGO3VKikQG1c3VX+CQyz4tG5ropWTt9VftfvjeR8VlxH+vTmUqEYyjbPT4Ke3SOM1RHgxrDsQvntDz6d5OvwMi6j+yKSDBKHVKQWeuDmmncp59oCwwQ+209cxAHN+pzeH0Z9gmZyKBp1U142AecpYEeX/2Wro+jLv3EqeshfxmP63+sHGTREkXlgZ5P+/RVne5clgKyVznZ6u6mEvn4mZlo8X8qnDLcl4Oc2FaHsg2gp/gGS4Nqk5KDxTRwN/uGltg7lJ4hLGR50mQ77mCC6xl33fgwtk7gt8VaMuVXQdv1BFUnkFC7LJS3iPyFiz1/4JhKgv3pjemZJe1vasPXigdgitB7v8O+
  template:
    metadata:
      creationTimestamp: null
      name: github-webhook-secret
      namespace: argo

