apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret
  namespace: argo
spec:
  encryptedData:
    token: AgC4jEdNeZ1ds5pKA23Pn1JeOFiOFtiurUmvFvdjJZhexoBnBvzpACnH5is17OJRgRF6bKnbuxaiGzF8k7xQQ/euvg+yVUJvxEaNiRJSES18gVFUTSdatVnP58a6j0kWotq12CqfrJjn1Zq0Ynj5I8SbpnWqNie2xCqLyfcCbaz557NnbLJKSKrGHmUVIjZnuTORlkyC5igPCi/vw+R6WEoYf1zObvE7WNrvmjTb6kTJvAhzUPTR1OiOxurhnl1emNdsBCuBomUn5sizUFye3j72Y1l3RwGgkn9rGy3vB6D2yJoMq8gvcczR8+8P7cSLEZurjcBFrAV0Jo3djHfx6iJU55n1NfENrsjyuFW/nGfhhrtnaHRE/rHFVgE0s5gy+yTaWd4d22Fnk5VJPhPDczM8+wbHH0KbJ2eHjB9uvoT6LHz/a0paFMvtVVrMWK3ydgyWsXZekVpe78EKIbMyrj7PUU7OEqGumeZo9oodGIVGfREikJgpIBIXsdh/bVFcAUIPxlSX3dAdIgzCOlJXVyNIlhwPaqcQ9hsQAKDHQANXUrSYiwGfUraRmHRoJpEQk6Un+JyiUqB62tUrxvx9WPKxY9A68GzafvGizwij1xA9q1mncFEX1YgQO9582VpAZ0pHpIcx3gDoaRZx23b+ZsXtWe1kDMTdj8HHywfK/lPV9ORVt7nZxwOQ76Eb3Lf7NsiBcjmYHVppFv1wsnLDiifVimyRbYrO/qssv96AAWDZVVQjs6WYnzGc
  template:
    metadata:
      creationTimestamp: null
      name: github-webhook-secret
      namespace: argo

