apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pulse3d
resources:
- ../../base

patchesJson6902:
- target:
    kind: ScaledJob
    name: pulse3d-scaledobject
  patch: |-
    - op: replace
      path: /spec/jobTargetRef/template/spec/containers/0/image
      value: "245339368379.dkr.ecr.us-east-2.amazonaws.com/pulse3d-worker"
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: prod-pulse3d-uploads
    - op: replace
      path: /spec/template/spec/containers/0/env/2/value
      value: prod-mantarray-logs
      
