apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - argo-workflows.yaml
  - argo-events.yaml
  - ci.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: cluster/manifests/autoscaler/overlays/prod
    target:
      kind: Application
      name: cluster-autoscaler
      namespace: kube-system
