apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- argo-events.yaml
- argo-workflows.yaml
- ci.yaml

patchesJson6902:
- target:
    kind: Application
    name: argo-events
    namespace: argocd
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "cluster/manifests/argo-events/overlays/prod"
