apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - argo-workflows.yaml
  - argo-events.yaml
  - ci.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/sources/1/helm/valueFiles/0
        value: $values/cluster/manifests/grafana-loki/overlays/prod/values.yaml
    target:
      kind: Application
      name: grafana-loki
      namespace: argocd
        path: /spec/source/path
        value: cluster/manifests/autoscaler/overlays/prod
    target:
      kind: Application
      name: cluster-autoscaler
      namespace: kube-system
  - patch: |-
      - op: replace
        path: /spec/sources/1/helm/valueFiles/0
        value: $values/cluster/manifests/grafana-loki/overlays/prod/values.yaml
    target:
      kind: Application
      name: grafana-loki
      namespace: argocd