apiVersion: apps/v1
kind: Deployment
metadata:
  name: operators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operators
  template:
    metadata:
      labels:
        app: operators
    spec:
      serviceAccountName: jobs-operator
      containers:
      - image: 077346344852.dkr.ecr.us-east-2.amazonaws.com/jobs-operator:0.0.1
        name: jobs-operator
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: curibio-jobs-creds
              key: curibio_jobs_ro
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
