apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access-token
  namespace: argo
spec:
  encryptedData:
    token: AgA0s3dkKtPJ1e3p53dcSdhJOUsDPxzuf+Aa2q07Kq7oGKUYlUkXMTyl4+3uZK1V5co260z12yIPdEwTCClc1/VAj3XpzWKSSJRpZ1PoEERshy65C+m+0eD2hDqsgR/ImEDktCvex/vSUc5IkBTNC2G7V63zaXgVMIt57XXmSrMTa1P/aa4LIotzkW5u8wOkO0Tit89jfinQgxKyA2ewQwI0gE0fQacoQmuOkBoSLmceBO8fUj5cwxpeQc21ZkIjzYsSX3uUjjYbL9xigiSTJzKRRlZuzRvtm+qg6te+0i4QFtaCotTfnPQQdAtLc0GuwIJXZoevvYE+cor9f6AidHWlHBIOw2IQ9kJet7TWE4xdwKIn5nPNWjjtI8znX5GctkrqJqR3w6zY2afkxqaxzl8d2ySSNFtsOhXrxT0aUbHmB2WFZhE5tSc8JaD8l1M2pCj0HMUGMscs98XBkOCIBqrVIauD2EFe9kdX4u2wzO+dbnonrLpZFn67/5SkeEEhZ9cVBD3+fdTddQSmOW5O0Jgmf2ruLjFmkyNeeKTprsnj2RtbhmsOgqYXgDXFugeHdbbK65MztQ2zaRtDlnhWQ3bXs6JtVhwvwAXqBjJrBSMqK6F6neSP/K7x4P1MsapwQ3sX8FvvLpRr0vWh3XxLsc6ZjiqkbHnqZzox5h1Xr8AsPtYnmj0dM9jI8C2tK3meDP9qBESYsrWosXIT2RmJ6ghTHe2nxn9N7dktLEHDvaDjC5S3NVTKWtUu3CJJ+6Dg
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access-token
      namespace: argo

