apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret
  namespace: argo
spec:
  encryptedData:
    token: AgA1jgCfhuP0h3NrshAg+4ZByjj4y/uiKKKi3ML5SLtjcZbne7ePVozh13RX2hsAaq9ZVCgLkMSIwmiwoZDuY2U+/AREIkclp+BlDhogZZr45NdGIsZ8qyxe0+cQJae8A5LO18Vg6GCWYcVc0b/WcC5OZsD1TtIahFcMkWNUqdo/Et0c1OCEFhyGAntv7h/WTSnlPDqG1/k84GHMUny3iIfW4W4Q4JnQ6gNol3EgpPi1UU0BjhJlf+j6r8hsq+lB7St2d50n0sJBOArecoen3hwMM7dmw/d0Ig4id1YT18NJNmXraLeICN1+hqt26rnSA0GrBvl5TeFtcWEzHtxOWLCgS9J/32lkS0JP+Yy6DynWHBzI+rrZk6Pg0PkV0TgxJCKYHrzmi7SQ7YJD6ozJN5+ZhazOYbWLoV4iYt6X+6ECvafXp4k9DCZJilWX0GhLUdYHcVGRdgqmK6mTaXTRKeN4JELXHYSAOqWVa3hMueLKr8aCksdoBkcmP899f/K0nWWXwKlPkWGERYRM2ZZAyGX5V8T9lObIEPyxF7qTscROR9eQ8fkP1XOQ1WClInwXMvbXA36GYAZX5w6uf0jSkCMnaMQs7BLPpvyGtTavS/TuwIz8ikfhtJgv8xUU+sv86Jk4T7oepj9Gxi8OggjdH4fZCKM5atJ8EHmhNDgq1wy/xvfdbEjV4yZmPdXCDZCBm17iQrBnwtkQkWJqm1NcBbDkJx4bC+gVTJ8m9rJTFwA5lkXz363jZF3Y
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-webhook-secret
      namespace: argo

