apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret
  namespace: argo
spec:
  encryptedData:
    token: AgAjdubhndFtNdjCJAzR0NTJO8WVFBO/uidlZjDUW++vLzdCdQjjtPfnxG6RU4mTrDmgVEgP/9crR97twFUyoU3SJ5I0dyXXEF28z7rI28zNlCYqBFNjpbj1XM9UIl/4S99wpOamoePHFaxOP/IyUy56UulL+kAHttEDg4Oo0qnByB/HYwcSyJrY4Ff+ATO5jBDSfRdeSzGS4HZQN0RAsasbS+yLbUxHj3DxPkSPQ7ou4gm7e4GhGE9EeU5uRVhfkD7onJKWSwYHzNwXzj9sJ9relf5lXZCNo9q67q0Hrf946ntq1+ioxsOEeLHZQzJw4T2dGRsPmpUVXToQINIZWNC01V8sNI7O4f2WsP4a9MZ67iN/nqCq0nvKam0k73viLeKyluA2IobWJNSlbWD5+8vfuHq3QqyB/zvrhuZN0mj8wngSRQUhQ4s+9I/gCyq+uU1+pAp3HWWatzgNokqwFa0LE6e9WQqWbg29aU1ZPTZo6jsEYCCIGyyEUEhSNbnGoEsxWiupVkfilvttnvFcq7ROdhzTUIvdr6wVlXvGUMwPdczgX4Cm/UwEH+j6TVH/+FvUvtLw/tJwjLXD77Kqky+Khc1cWu8YV+A0nn2TY5XzfIIqd9RJKsG5lgOd5OltQRE2KzAkIRTDMnIXUyvhkQGQGwhnrp3fErllf3a82CdheAkXMk1Xo2IXF6/A3BzoTtcvOccWdhiyWk97yGRD01IIA0f75le2JlPwGhSIwLMLLklNieAmP7Kl
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-webhook-secret
      namespace: argo

