apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret
  namespace: argo-events
spec:
  encryptedData:
    token: AgAbaciBmma8wmDxnFsnhb5RJgxO5DjzWEPW3vzF5JvYlt03MMoQ0d76Q0porMR3TwnPnCOVAu2zjRmYDU66apFxqXQdyy0hjdD21P2mtsKlga92t0DWPX4XkdCmHpxHmP2r3qp4Gr5hha+Ku77IhaxhTq8KzwQyPabiue3Bug5nGnW2QNZePs70DIyMWYDFuPD7/Qi5JPy8FhhWDV12mVNqL7P1/JakZmhjO1OqaFUfrznNwwgc7zgNPb9D10UY7moR6gCf5+DMQc7G0qr/Oq0jsXyoZG/yrw9ZU/XZcgtcoAzksA2SQ14LtjObwQWIDtAnxpf291qvpm7AJUrK5UifZ5IhRFuwFEgMXDzd+OSDQ449kKKTxaCeD5WU7KVeCA/jZgHPM0Qv2PUAU1rAeWPm1K0vlWinkSc3pTigqn7RDAfxhftM6daZ9C3yex+Rs+Hlx37mN2nEGmsJzXmiWWhUewR8KjY51+8b4B7AfTSI47hiOqCFZBZG6tH0IqtUZtr/+AZmA+WBfMszlJ1DdBnITTBfq9yg+N9utwldOJmCt/TbOHyiwD+fWAWo10NXqDWr/yBmSE9GncFfHOun9VN5Gt8UBDNlRNpXJsRWZarElRHlhVyps7nIR7bV8DO9FoneSjfcWollwaLZpoFJMmqpJxXMArHtE05JpAMkuuV1surynsLTJTuEX1cxG7sEgIfkZEQA5iFzwgOxWUgLa75JX3Gy5H6RYN95/F6q/FfXvCEYxIri3SHQ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-webhook-secret
      namespace: argo-events

