apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access-token
  namespace: argo
spec:
  encryptedData:
    token: AgCoXpbJnV9a7zYpTLFwJ857HFHjliocwFgXvSl1tjij9RXEjAZgE8+lBaHtCKaYfCq7XgRHOezyrMwSfRH33eY9B2MfH+k10VfCtQNNC10W4kp9Tq1H58PL+yI8xfs9NFhlT9ldQNCsHnv2bUS6Q/lseh7vt7wcAuXU2ZNqFaMH4vPSmgKr3QML6fwVGczUGw9uCJsfQ9ytoEM/+3Uiqlki/UUlCnxDfn6ZZ6SunZdmTrrt8Tws8heuQzVNtNGCJkQ+WnWPAgu/29qYA0ZDd0ZI/2X0o7QfGQ12IbV7Vs2F2EKUbTbDwseK0b5RiDY2L+qpJbdIyBeh2HQY6uq2+dkxs1h/IUtonrkqT88uZ326MskLa5nL4+ZrJBV/64nZfgQtDWW0Z3HnN70r15j8+uWCrzSsMrxir3ODz6U3N9TUUoNZh02X72MUUIuWRCkuU0+4Vh7bxhIbro8d0rPFbr3kFgG0a1yi8iWU7vxWntLsUI2TOVl/zlG1rKijb45p3ut/8LYOz0tBugBmBab8uma2kDJuRLi7Z0xU4Ln7eZSxpsBoidsbHPwZ/cQD6lMfsdquELaTHJoR96zNVsC8rXl5VK6AO+/EO05PZ70iFj7gv+ek/aA8opuDhVmjonX1rFO7YHzzvS2Nbe4Ih1OTqPiQu80B2jPSFGD7vWyAhca2kyzXOIXSnuRXvruwMWp67I9LC5/fwZzKqXGNVQTK7WqTH4MKXJ/sg88rA0/SCYO1DIJ0GkiTb//Z97AqYx86
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access-token
      namespace: argo

