apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo
resources:
- event-bus.yaml
- gh-webhook-events.yaml
- github-webhook-secret.yaml
- github-access-token.yaml
- https://raw.githubusercontent.com/argoproj/argo-events/v1.6.1/manifests/install.yaml
