apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: curibio-email-creds
  namespace: apiv2
spec:
  encryptedData:
    curibio-email: AgA2ZrQtb2onNVuyD/1rI34RCJZJHg3uwGzX6HOnSg5311CZHW4fFCnCRZCw4pv3xgxp2R+s/+7OFny6AynRs3cPuSvn78dG4n2wBs/a/vOdteAZM5vmiCuJh9gVo8fk1AF/uoNqcA+Zr5i4RgFhF4zeikQltvzW4+xglFXLN2FKPtxT8NZWspf3+KFKG8G3lRA8He0yvXj/Vwi4HcdBgiadjLIlXoSkTu9Jgfxzwhb4xpWjwrseVIYxsrt/ugol/O3AyrcEP4bv6qcf+H4/KIpsiGZ/Q+v9CG0BrQ9q+IuCXP5hGgA4HQRW1TKMK/uIaaQUrHF0GHtOL6nYdFYSCsYBMqufIPR1lAFBcWiT7P7OXrgmD552vjB4assbnHGEOo8G4+UXhR0tKXJix1H+qm5folbLzCu3ME2/bAzSzOGUUzGbE3ewQsHqAxUCpwiqH4ly1av1ZzjXMYylbOr7GJEeQWeIKODZBKb6wc6ihYOn5EuGgeu1lj+wzqTJb79Nck4IDjoxCcI/ma4KSIod8GnirQGCliyNmzGhivPNpiW5PIwchipZstdqRUznj+U/tY2SQXj74Cp1MAnvRu2VkEu4kZx06a4rr69SgZxTXWgwaU9XPOLwOizq34EQA5EBNwTzu2ETZgdjL/87at2AQ64QX+52KvDCkvc++vPUpKj3TtMvh7uS4BavF4C9miwK+yksLEflZPdpFkpFPvkpsWZrFZ1YC0Q=
    curibio-email-password: AgCyo6BA2wzTLkAtR2P+TvkYhEPUdRr78Q4/q6I6uD0af4HnLScZUJ08C6qc85e9GlKjQjDWVjR613RS0Xn6gQRRreemZbMvmpI0murLq8EVy2VIgFxE0ag6POFcIsko1hZljkgm5aYgQ42MjIWTyCV7Ev5FyMx11qelRPzMO+LHj+TyFoxdslwneeCoLavtOxdppAlfs8w6J3dEpYqUsQCzf+Tai/V7dd0F3CeEMns+lYHqLt1bQUfQJdVIIdB2evCI7PJPYtnOjA6L7gWWxnsHgi95vlb2QAF8rgXcPSxgLStHJWJAvVVI85RIHz7XxnZ7ABwEL+QLRY9ZWQofQj7YjwG0eojVtFF4iqTcIPlOIzoYbkp01WvtyOxMOk18v5WrWnSK1xeB7ijq4Xx24+74uWsyBI2sVEvU3wWWEB9neQachztIfCpYiDg6s+Z+yWo1Uuv2s25qSk4lT9hNl2B0dC7tGhaBjAhpGuKd3r//NWTVsuzSlURID1t3smvnlziDi5xZaAalB3WAW6iHJG4I+lO29KLfQ5S8U5LdaKkiPVft8t7uEe7m6VSLljXdBUVXyJLH9ojz9AjHiRGggAgc4OUiWZpszUq+zyjY6ioQeDgH8m/iV5idh2TRlD4Dfw4lZIUw7dKudqmTtvoBqLB1gG968bWEtmi+8/dHJIxZmuykb2DXZ/yR7eqojU4EnkYmfdFRz1UK4rP5CYGS/O3+r+E=
  template:
    metadata:
      creationTimestamp: null
      name: curibio-email-creds
      namespace: apiv2

