apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: curibio-jwt-secret
  namespace: apiv2
spec:
  encryptedData:
    jwt-secret: AgBI/MmyQ9L9G6PzHwQbkPVFERGyID0sNP0FAQiSny4yOfqaSWQZtBXrp3WsirKdrxNEGg5gxzkyaqZQO+vo7iwbF9yXpkMBYlMDG30Bj2nhW8cBcEN1iaPJRjZmHCk7oP1oNxnb7ycb2GZ61GzFjTD255Soi0/P+xF+I38/LLx5L6yl31u5aeNzwjGSm/5HKhRBLiKYBX+cjMxITU/D6l3EWtsrj0qAtdh1PWpzO5ut5KXEyt/6iBOq01l9maR2L43rv782xUgPJn5SGU5iuEFF4/v4i+BxY3jdpKxSO5ssoPTosSYz6iZeeeX1XYPkDRbU9nbDt9nkk+Z7DN2KJJE4jhgzDa07bLgR7FcgH3yPHeIVrQELFANMAEXzC0ErMQh7R81LreEilV+yRVgMIhwVfUKINnRAy6twvKK5BEZHadodAbeCaDoHJ1t9yOLeXqt2VB9XFm14IvBLHY8NVgiJGn69PpH5YAFQOBXuxlIGzT+TOxEh85eJ70ZL+XEdrebS0aXfEy+6cXXizR4L6UBP2H9ihVVu7BLLo0XmVH2SBQLRR+6bXKTqwV/MIZ4eYA0DS9O8YaWYIInsPnPYad/uFAVx33Kpe9/43zt5VNlkoxQkcahufhfGnNwNewExMEuGQMNwkwzeYYkmlgNGT0TH2Xo2OYq+xKE4FfQi6h75o2Plk6vxn7KoxPSXSlCEPsgin+EcYqWtEHReGWOWMUfVXnIKaGwR3Ng=
  template:
    metadata:
      creationTimestamp: null
      name: curibio-jwt-secret
      namespace: apiv2

