apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: curibio-email-creds
  namespace: apiv2
spec:
  encryptedData:
    curibio-email: AgCkhgieefJyON/dTpvlufQN6KoTt8f5VZ74hBPiHp5d74+/ykA5l54lhUu0hlTeIV5ttxxu42ivI9gds2gzatPr1JlmRh/0j4QHZBVbD8HFB1THttqiE2bTlQ+lwSduT2lcmSE2uBXYbJ7DH59Ja9hl5w1VwYzBl/DUITspwMalCEEmHuAMFDx+rQ8HXyMN4W0yMZ7gLcnrHYdTzuc2MCV+HlLUtVAphee2t3VaaZpFZOwpKnOZbTg529zXY/OUSNZidKmlCgauxb6mO1FjeQvU/aMmcjwD9wHfzeEC39JCHqNRTgYwP3UWLkmuw4TON5uK4ZyASqX962f+r7wLY7kouO7zC1yz1GS4S1ttCSEU3upCx45uJ84Gz2Y7RlBATaxUz/Rl4+VlziOIzOeAoRr2aUjtyti4zcAa141s+M12L6pPvk7hOdTk6aKUk5F9ETpe0G5BdT78aTNOG1RLn5BVWHH0yxWEiIKXnn7GMqOojXYWNPlNSr+HrHHMym4lvu3LEGF0V2A1bKDvHUdrRLz80psCHI+VwwVJ1xYEgqgdRJtFOHEbkx2ezdxc5ra1za6PzVHA+/ePQFVr4cV/LZ2I7dsKJLgJLQ7lA3Ch3VriKjNqGV+qvjiDbCM3dvs8V9yDhItpypBQ9U9/6H55zotD2kZwVpcwpx77pyXOi4eWjsCifklml5KqUCvVJJpKBv47tkNf9r82vkbkMLXBOLRJNxIb6LU=
    curibio-email-password: AgAYM5B/XKPGyL85gHdJBa5VUkYxoX3PQAvnE92zZphRSBQu95E61lRrAi1pQjqL/8tVItIq4lUFdfH5Zy3JNWwXQ3kwL+Y96fbmNPKNg4lJJSri8ArzK9FtR2/pav9Z0jq26yAFNQPuGN6g/UAs8VSesx9WpyR4aRD+VJmQwwK08s/9W1HqfrbCKXGSQcHIrXA6liex0e0hbrhf8k1xc4m4c6DKER26op0AXUp9Hd8Y45SnIks/3I0Yq6MwHtIUhlqwedfxP6Yhoyc8m3t8JoqhwAtCFtL9o+WNdtD1D+ChMf3EoSlG1H76WGUGaGJNP+JZ+Vo5UK5SsAgsJSlhozzJv9NiSAIH72jQy1rLkvw9WHM5eecq3nOi6cjRqdBSZ+m1xJ6/QSV+ffbjyxMadJIAMMYpoGoV1wvVFVUrawNmte4bo2/mtFeUkbmvC1z5Udqc1uisa8MgbeJl9cuzB06lOH3rIlcmlC7M1KUWlrnO2iPX4cFxJsLrE4XlBnFGBj6NSO48U6Mi7vz8i4sfN/HRB91m+G3crmaJ7O9+orQNAklNlhS10/k/RVHsi+IiXAvMGFQKYUH2L4IiIpGj9tEm39mVZ67PPmKAUASf/vUgteUq1hl6gBCIq/mC2VTwSQFxzrkKGgtcPzgE9hHzWJe+V5ehGszWWHkFZsKLxjGICu0f7QL1E5gCL/0i24QHYRFHOQkcG3zVDHu08yEeSWeUow==
  template:
    metadata:
      creationTimestamp: null
      name: curibio-email-creds
      namespace: apiv2
