apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apiv2
resources:
  - ../../base
  - curibio-jwt-secret.yaml
  - curibio-users-creds.yaml
  - curibio-mantarray-creds.yaml
  - curibio-email-creds.yaml

patchesJson6902:
  - target:
      kind: Ingress
      name: apiv2-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: apiv2.curibio-modl.com
  - target:
      kind: Deployment
      name: apiv2
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/image
        value: 725604423866.dkr.ecr.us-east-2.amazonaws.com/users:0.6.2
      - op: add
        path: /spec/template/spec/containers/1/image
        value: 725604423866.dkr.ecr.us-east-2.amazonaws.com/mantarray:0.5.0
      - op: replace
        path: /spec/template/spec/containers/1/env/0/value
        value: modl
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: DASHBOARD_URL
          value: https://dashboard.curibio-modl.com
