apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apiv2
resources:
  - ../../base
  - curibio-jwt-secret.yaml
  - curibio-users-creds.yaml
  - curibio-mantarray-creds.yaml
  - curibio-email-creds.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: apiv2.curibio-modl.com
    target:
      kind: Ingress
      name: apiv2-ingress
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/image
        value: "725604423866.dkr.ecr.us-east-2.amazonaws.com/users:0.9.4"
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: DASHBOARD_URL
          value: https://dashboard.curibio-modl.com
      - op: add
        path: /spec/template/spec/containers/1/image
        value: "725604423866.dkr.ecr.us-east-2.amazonaws.com/mantarray:0.8.2"
      - op: replace
        path: /spec/template/spec/containers/1/env/0/value
        value: modl
      - op: add
        path: /spec/template/spec/containers/1/env/0
        value:
          name: DASHBOARD_URL
          value: https://dashboard.curibio-modl.com
      - op: add
        path: /spec/template/spec/containers/2/image
        value: "725604423866.dkr.ecr.us-east-2.amazonaws.com/event-broker:0.1.0"
      - op: replace
        path: /spec/template/spec/containers/2/env/0/value
        value: modl
      - op: add
        path: /spec/template/spec/containers/2/env/0
        value:
          name: DASHBOARD_URL
          value: https://dashboard.curibio-modl.com
    target:
      kind: Deployment
      name: apiv2
