apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: advanced-analysis
resources:
  - ../../base
  - curibio-advanced-analysis-creds.yaml
  - curibio-jwt-secret.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: advanced-analysis.curibio-modl.com
    target:
      kind: Ingress
      name: advanced-analysis-ingress
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/image
        value: "725604423866.dkr.ecr.us-east-2.amazonaws.com/advanced-analysis-api:0.1.2"
      - op: replace
        path: /spec/template/spec/containers/0/env/5/value
        value: modl-pulse3d-uploads
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: DASHBOARD_URL
          value: https://dashboard.curibio-modl.com
    target:
      kind: Deployment
      name: advanced-analysis
