kind: Deployment
apiVersion: apps/v1
metadata:
  name: pheno
  labels:
    app: pheno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pheno
  template:
    metadata:
      labels:
        app: pheno
        version: latest
    spec:
      containers:
      - name: apiv1
        image: 077346344852.dkr.ecr.us-east-2.amazonaws.com/apiv1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pheno-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
status:
  loadBalancer: {}
spec:
  rules:
  - host: ???
    http:
      paths:
      - path: /apiv1
        pathType: Prefix
        backend:
          service:
            name: apiv1
            port:
              number: 80
