apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-pr-merge
  namespace: argo
spec:
  serviceAccountName: argo-workflows-sa
  template:
  dependencies:
    - name: github-dep
      eventSourceName: github
      eventName: k8s_curi
      filters:
        data:
          # Name of the event that triggered the delivery: [pull_request, push, ...]
          # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads
          - path: body.X-GitHub-Event
            type: string
            value:
              - pull_request
          - path: body.action
            type: string
            value:
              - closed
          - path: body.pull_request.merged
            type: bool
            value:
              - "true"
          - path: body.pull_request.base.ref
            type: string
            value:
              - main
  triggers:
    # https://github.com/argoproj/argo-events/blob/master/api/sensor.md#triggertemplate
    - template:
        name: ci-build-workflow-trigger
        argoWorkflow:
          # https://github.com/argoproj/argo-events/blob/master/api/sensor.md#argoproj.io/v1alpha1.ArgoWorkflowTrigger
          group: argoproj.io
          version: v1alpha1
          resource: Workflow
          operation: submit
          # metadata:
          #   generateName: ci-build-workflow-template-
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ci-build-trigger-
                namespace: argo
              spec:
                serviceAccountName: argo-workflows-sa
                entrypoint: ci-build-push
                workflowTemplateRef:
                  name: ci-build-push-workflow-template
                arguments:
                  parameters:
                    - name: title
                    - name: number
                    - name: sha
                    - name: branch
                    - name: repo
                      value: https://github.com/CuriBio/k8s_curi.git
          parameters:
            - src:
                dependencyName: github-dep
                dataKey: body.pull_request.title
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: github-dep
                dataKey: body.pull_request.number
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: github-dep
                dataKey: body.pull_request.head.sha
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: github-dep
                dataKey: body.pull_request.head.ref
              dest: spec.arguments.parameters.3.value
            # Append pull request number and short sha to dynamically assign workflow name <github-21500-2c065a>
            - src:
                dependencyName: github-dep
                dataTemplate: "{{ .Input.body.pull_request.number }}-{{ .Input.body.pull_request.head.sha | substr 0 7 }}-"
              dest: metadata.generateName
              operation: append
