bucket               = "curi-eks-test-cluster-tf-state"
key                  = "jobs/hermes/hermes-worker.tfstate"
region               = "us-east-2"
dynamodb_table       = ""
workspace_key_prefix = "env"
