---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: curibio-jwt-secret
  namespace: advanced-analysis
spec:
  encryptedData:
    jwt-secret: AgAxz87mC47W/ZDt733ALIlY/vDAxNc4tPbLN6oa3/AnzWtuURclUyn4H9D1aapQS7ENxS0FBpRnZXkDlrcajXQG6/9oCPnU8kdht8HWlp9Lldj6J0xhvMJPn9tKjASYOhOhwFlix3cCBI/9fm/HTk1ZYFI7Hb1jsB0dLhUbCa3mYJo5mEudfo1xVvzLxDKbhdiMeBJVpFDJjmb1/wV1v7uo4K5V1gvAVD0EOVwHJiZ34vjTkZBDzk0Qp7BCmBwsx6x2OTWmtjF3zgqteGjYxVDku3ID2KzYdfzb+HeHh18ULZuR8z3BZ7TvJjdDsPc0+En2wRMEXZolgR2XFSVdjxFRnwItn18LKI6JvHSd2UMJItu9eTZ9VnjW4k1cBzb/Ft/k9zG3nhboL9QvBNt/GTK/zM17RYqwEc1qTcaRz7USqU2ap/g+h4vXS4fRWRK/ZhoKfTkw4tz81OMOMCbmKQG/UsL6kQPIQQClonlP3da/8R8pHOIJrwLAQ0Ouk8bXaxbf66IvCobxOnWC2ea8i024F8O1NUdVUG2nX+bJ2O9evAGBNakeCJ/6fvFdEMKrkvagcfHmnyQ7C1g64gvNhSjPc3AkdJh/skN/z5m1fwEvQApgUEf8mEgjECxFT5jekUYHL25+gR1IRh5cJ0ExsJJ49UtMJTUXUj9T73TitjUfmcFkdxj58gCxd8PggLzcLNXfDhP60MNfqC5dc1hKEiFPyicqrvxcuOg=
  template:
    metadata:
      creationTimestamp: null
      name: curibio-jwt-secret
      namespace: advanced-analysis
