---
apiVersion: curibio.dev/v1
kind: JobRunner
metadata:
  name: pulse3d-queue-processor
spec:
  job_queue: pulse3d
  max_num_of_workers: 8
  ecr_repo: null
  product_specific:
    pulse3d_uploads_bucket: null
    mantarray_logs_bucket: null
    min_memory_mib: '4000'
    worker_db_cred_name: curibio-jobs-creds
    worker_db_cred_key: curibio_jobs
    worker_db_user: curibio_jobs
---
