--- # PULSE3D
apiVersion: curibio.dev/v1
kind: JobRunner
metadata:
  name: pulse3d-queue-processor
spec:
  job_queue: pulse3d
  max_num_of_workers: 8
  ecr_repo: null
  product_specific:
    pulse3d_uploads_bucket: null
    mantarray_logs_bucket: null
---
# Future other products i.e. Nautilus, Pulse2D
