apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- ../../base

patchesJson6902:
- target:
    kind: Application
    name: apiv2-deployment
    namespace: apiv2
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "deployments/apiv2/manifests/overlays/prod"
- target:
    kind: Application
    name: pulse3d
    namespace: pulse3d
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "deployments/pulse3d/manifests/overlays/prod"
