apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: "deployments/apiv2/manifests/overlays/prod"
    target:
      kind: Application
      name: apiv2-deployment
      namespace: apiv2
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: "deployments/pulse3d/manifests/overlays/prod"
    target:
      kind: Application
      name: pulse3d-deployment
      namespace: pulse3d
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: "jobs/pulse3d/manifests/overlays/prod"
    target:
      kind: Application
      name: pulse3d-jobs
      namespace: pulse3d
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: "jobs/jobs-operator/manifests/overlays/prod"
    target:
      kind: Application
      name: jobs-operator
      namespace: kopf
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: "jobs/advanced-analysis/manifests/overlays/prod"
    target:
      kind: Application
      name: advanced-analysis-jobs
      namespace: advanced-analysis
