---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: curibio-email-creds
  namespace: pulse3d
spec:
  encryptedData:
    curibio-email: AgB4zlvU2NMCE0iirjJ7oYBX4ww2q9r4NpWH7TypGiZZD6xeiwT0Vu+XNP/Oj5CgtXmnkXDBH/Y3IpXfu79lnLVvrZLRz2fyHPL8NiQ0ASDOiEcuRx/aExbyR+pqkDlpB2CR7vvgGopGOOAtwswcQfBdaW5p2Gcin3010jR3ftYY4ZAZCNohr50t9e+jl2Ac08p+4jxkTPaemeQ73h5JJoWrXWQtd+FUFBoPWsoCAxERqnnu9cAEnvUQjwL6wuyyPnVr+y4gMeZ3lT9Xtm7NbvHIFy7dr4cooec1e6BjtL4HQEttS7aa/nmzTN/t6f/7dVnffJ2rd9bjGCqkrIwcuI6z+QQISYO9KHFkj5GvXpnwgrQsb9CqcU/mH4K94AHbGbH71JnzbnkejccZm9nzJ1eV0yMm3Yfoi3PfuHzMQ6VZ2EjXUtMHaSMOdtJVrB3OhHwFZCDXfdEG+/85zhQSridrfaEjlU2hUF1wBq3aKqUrjeLgAGpPiaHUtCNPFIh0Ce4MDVVa5PHlxSS5PTx8mzSDh0XIm6QaIerM5LokfuDP8Fy2dmjpIbth+vVxhN5nsLvIKvclRLHQteq2RE7K6Ho6NIjx5q8KkDZAxTxm6dZ9c7jV32/488C5bfNp9KsXfBpljaCzMh9tcrCpcabzUbyO/08uDpuWNkigZ+/ruwT3CSGTA+A8OMtdZzYmm+hpSpUuh/znoXxwLqTckZRgFjQVBhqrIJA=
    curibio-email-password: AgCBnP/jYUjnHrN0lt302dIF0OQlzOffqYswOD1aU2xdVZLS2JigfQX/aKm2bnC1T9pJSoLSs5wQh4pRzk2gVeqaDF35gb1FJNRrf02KDcvLPOqwVGrS0sXB5Wm0Yt6vBbrryK5Abet+vsXpKnzl2wdflDZhzLIcJxF0Ciw9/N1YtSc+nLpvHdt7Iwg2WfXLlX2XkczI8fEoGCXFZ28rE5wSWYHvFGFLNQlB1ZbrEKr+buDyR39f3fkBcSZh+FTPIgKDsBGuIIrI63kX8h/sE10SdCLnz0jWCubuPGjWz9QwvpQZMzHtb4tpUWI1s74JgEt6DErEkV62IyaAPWKD7ySehVfwjWjsSZ6uEskMmhPFFOeWWaW7yY/ArpAHWqWK9eEGEcn1kCKtxFh6mFP9FDSYjW3X/ko7vdD//7ODtUBpd/J9yfV+Bnl2bP1Iu1vFs77hy1NnQfZxWxUw5mpiEDNg7YIBx/0kpEDDW4wy8UH7cVue/J2w8gCF8GCyk7luhroP1V6T/gLW4MjlYOfHxciWsyzITyRKaSP7WUpaGWEb9s9LmGaFyejm8He0TKkmabQEVdfjsvZhCCxp3wtFsj9fJ55HxHabNjQ2PVIkExyCbGZ73+99CwjDzXUQb3z9E1evCGUO6Y9LHwaAOTyEm58VfZgv9BBzdeMzbT0IAlETM9Td9a8yNY4yl60lDUpnLkjzECYAWn9w7BetHBoSh1a9WA==
  template:
    metadata:
      name: curibio-email-creds
      namespace: pulse3d
