apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pulse3d
resources:
- ../../base
- curibio-jwt-secret.yaml
- curibio-jobs-creds.yaml

patchesJson6902:
- target:
    kind: Ingress
    name: pulse3d-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: "pulse3d.curibio.com"
- target:
    kind: Deployment
    name: pulse3d
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/image
      value: "245339368379.dkr.ecr.us-east-2.amazonaws.com/pulse3d_api:0.5.3"
    - op: replace
      path: /spec/template/spec/containers/0/env/5/value
      value: prod-pulse3d-uploads
    - op: add
      path: /spec/template/spec/containers/0/env/0
      value:
        name: DASHBOARD_URL
        value: "https://dashboard.curibio.com"
