apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: psql-rds
    patch: |-
      - op: replace
        path: /spec/externalName
        value: modl-curibio.cluster-chen9kcdgdkw.us-east-2.rds.amazonaws.com
