{
 "title": "Login Attempts",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Successful User Login Attempts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum by(customer_id, user_id) (count by(customer_id, user_id) (rate({container=\"users\"} |= `user_id` | json | status_code = `200` | method = `POST` [$__interval])))"
    }
   ]
  },
  {
   "title": "Failed User Login Attempts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum by(customer_id, user_id) (count by(customer_id, user_id) (rate({container=\"users\"} |= `user_id` | json | status_code = `401` | method = `POST` [$__interval])))"
    }
   ]
  },
  {
   "title": "Successful Admin Login Attempts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum by(customer_id) (count by(customer_id) (rate({container=\"users\"} != `user_id` | json | status_code = `200` | method = `POST` [$__interval])))"
    }
   ]
  },
  {
   "title": "Failed Admin Login Attempts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum by(customer_id) (count by(customer_id) (rate({container=\"users\"} != `user_id` | json | status_code = `401` | method = `POST` [$__interval])))"
    }
   ]
  }
 ]
}