apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobrunners.test.net
  finalizers:
spec:
  scope: Namespaced
  group: test.net
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                job_queue:
                  type: string
                ecr_repo:
                  type: string
  names:
    kind: JobRunner
    plural: jobrunners
    singular: jobrunner
    shortNames:
      - sk
      - sks