apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-build-workflow-template
  namespace: argo
spec:
  entrypoint: ci-build
  onExit: exit-handler
  serviceAccountName: argo
  arguments:
    parameters:
      - name: title
      - name: number
      - name: sha
      - name: repo
      - name: branch
  volumeClaimTemplates:
  - metadata:
      name: workdir 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Mi
  templates:
  - name: ci-build
    dag:
      tasks:
      - name: status
        templateRef:
          name: git-sync
          template: status
        arguments:
          parameters:
            - name: title
              value: "{{workflow.parameters.title}}"
            - name: number
              value: "{{workflow.parameters.number}}"
            - name: sha
              value: "{{workflow.parameters.sha}}"
            - name: repo
              value: "{{workflow.parameters.repo}}"
            - name: branch
              value: "{{workflow.parameters.branch}}"
            - name: status
              value: pending
      - name: checkout
        templateRef:
          name: git-sync
          template: checkout
        arguments:
          parameters:
            - name: repo
              value: "{{workflow.parameters.repo}}"
            - name: branch
              value: "{{workflow.parameters.branch}}"
      - name: collect-services
        depends: checkout
        templateRef:
          name: collect-services-template
          template: collect-services
      - name: build-services
        depends: collect-services
        templateRef:
          name: build-service
          template: kaniko-build-service
        arguments:
          parameters:
            - name: service_path
              value: "{{item.path}}"
        withParam: "{{tasks.collect-services.outputs.result}}"
  - name: exit-handler
    steps:
    - - name: succeeded
        when: "{{workflow.status}} == Succeeded"
        templateRef:
          name: check-status-template
          template: status-success
        arguments:
          parameters:
            - name: sha
              value: "{{workflow.parameters.sha}}"
    - - name: failed
        when: "{{workflow.status}} != Succeeded"
        templateRef:
          name: check-status-template
          template: status-failed
        arguments:
          parameters:
            - name: sha
              value: "{{workflow.parameters.sha}}"
