apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: curibio-mantarray-creds
  namespace: apiv2
spec:
  encryptedData:
    curibio_mantarray: AgCVvV3zWaMfOqm2HyCjN7WOD4QRqzCU6CSNgSisxwUVvFJrkMMWVigZ7NbrDaIxyYjJyoL/xImUveio5HQHpiCL9aE/er9JeD8/MUvePeAqO1Hprf1LVr8NWT0j1wNla4CQrejVrSYvBsV4aXUQ60hwGwMxTrDIViH9Hm88GiUFl1e/BM2BE89Aq++ZEMewBjy/Z2FoVVDse11VQgMqzMWlaNj4nf+47BHXLmCttqjUMje79LLU3jqW4QVSUcEIuqefJBOn7d9Nmjz/tTdb7La6LawfZTZUauDCsuLlOydD72fCTIQAtk0nFu48lU8HQbnHm/Rm7MBK1i6DqH71Wqkz04zcoZsQlLAJMIMP2amS4DWE46ncz/Ts3bS3dogW9PhJP4BPuwpJytLgB5pWmQWdKpUruASvRleU3a8xnVucwPwW7rbDALYLx+tmwN8bA03MtIENzhCufxVEXI66IT7OKgHoMivdqN9yN7cM/+5jS5bsLFCT3RqXg81FJtYB38Wckx1EG4IJp6SVesR5b0AYXiU0qthoc1EYLm+Bd4IL6TVWWoAaqT/U1t7t/JSZVRFi7rNQ7OIztJ8/fzYqSTRnaYURCjItKbsPylFLBT9Q7kNiYjviTz9z0JrIuLcS6kO9/i+7186Omm4b5gsbHbzB7n0VcW55twtygRQNJFPoSC4bNqRoOhPxLm+MWzqOE6uY35jVoE/HK5cz0lE5JRa0P4Bk0QDsdOU=
    curibio_mantarray_ro: AgAYCvgLtmx0GcAqkRfX+5oi8Aw3IC54hfy+5j/dSxDLiEWzYNkf9PsTAGG7k7mIdJHYie2T6Ie9AiRh3Nm5v5bsJhuNj22WdnSnN8raobTP+6BQu1mBNnGMMJo29guRQvKNTvwjxAvaEJk04wkWAY3Gamt+by11/hjIQyGiiLer/ag5ly0HmyGWtoNwYS7LWYjxu959zCv8VXfyXFnFWSRDxzoNIYjw9cwBTNOIfsY5RX0X+UBG2jBubFTJIoSSZPHfQJDT2If8T3KyyvjkOaPwXfK/2h8ob8g47Py/6CAzfbiG3R518QgWOdfa4ROev7VEXGOMaeAN+uTGEC/FoOMBQlI33Fr/bWkoVoqJ16zhrLQjMZu5WWwjzkT9G6EJWF0OIbmXTiivVpLgU9upYMPdKJSTaQ1rUpQ8I55SUpBDQi2ThQKBRAFbLRsUgK9ELGrFpTdzBvNQq7DME8ieVqNqS/zzGpkIUswaPXW+NPHuKGF4dha00OPfA1i+GRYmW40gt5KsnZMI6XsTJya8UewJNjRkOHo6wqBC3B94NKJCc1Gi+tbmDYRZ+v7YYtHLBJN/bbXG8mkWsLRXX5xqYVuO700sNE2V1yGm+0U7X4EnrQ3b/+H/0/3KdsTJqmQ04gZE78A/2YJH4U33BmCyEeglKM4aSdkhREx3TAUNqD2FRBaGgiCqXQZKD+t3fhqy42xytUDZq5BwJUrpHD4pxbcZ+RWdW6Jryrtr
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: curibio-mantarray-creds
      namespace: apiv2

