apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: curibio-mantarray-creds
  namespace: apiv2
spec:
  encryptedData:
    curibio_mantarray_ro: AgBhObmOkKbnM0Bmhdo3cTZsLnAcuAQ0mlwQoW1GHkn3DgTCnAr5IE2g1BBfabcrrgLVzSJG+1UIjLU7raKGr3S0bEqwktilbfsTS6ujb4WJxHojhLCIe+pG0uZ+js4LIloH2WGALhOJs49tzq2UQm1bqRqSXw6iWg8tzgCma1RvUI1wDA5ibLeUVu8kAf8vx9wvekCupfE4nG52wu6fwnnPEPBKK9Y81nwm3cDTXjoMkNzyD31L9eL0EFiTXhrRCCu40I5vSHucU7UiHBjSMbE9nwJF0HRTAoWj+TjpRx9ErsV2lk0EgQx6NrYonQ3NitiZZnydJVFIZDfUovuK+m2X5dwSYhCwFNj9YGgff4fes+UbGhVLop1bsn3aTKkI39dlVmSfX+rklE3dgX3QawcMu2PgPb5H87ev40cGTxFRWYeuuav8KQnxShNGO7jmu4XDiPbpcoPaSQKvfz/l2Wv0rtJIRSQa/Kh08+mw/mWCDRx3I333wYPujYCv7jPVOPxzg5GIP88n9KOti9K52HIIlE5AuUzTQ0UHCDejHg2TRNW9JFy91dV8QMmGsMIfm5fdqvePdceRD6KuEz92QOYzfnC1F2MfDC5XJel/EvrAwlTIAbPEfuhIARNuHlSFK/GPC+pe5DmjsXadinRktXHIjqJfxY+5Cz14a0uDAvaXTO7v3JtnJX/+HmQ34XXitXIoGIsF9HTEvsjg0q6RM6rFH7EqqWRk4Q+D
  template:
    metadata:
      creationTimestamp: null
      name: curibio-mantarray-creds
      namespace: apiv2

