apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: curibio-mantarray-creds
  namespace: apiv2
spec:
  encryptedData:
    curibio_mantarray: AgARzx3P7qqW2+WrqNVHN2iWTUOipmhPCnHZHZRmE+Ebd32cyhkR/7DFDhlgyVAqTAui27H1AwKO7zndahqT4niWy6bD9guaY+nySwTpgpZq0P3ufOa3o/J3RjxTuNyN6svoMbe8cyptWBH22MfZoz5eXFq3OSvklCGXoXPbJjgNKdifHtmzlIvZ19tDzJ39rn2iZEkFm9oz6uzcortm+3FXx3a91IBYsRrUSOSPNQ/q1yg+gjsXyZlc1WPIet76T5AoPgRW8DmP1GvY8Hr8fVu/UOwfkf2Smdqrh2s7aOjOdNNVyFOvZUp+9yq2UFRqnSKjyFXs1+ryoAhg43NTQSLPALhf/xojEUq/+80cWkHiUGU1+94PNE7J7PkKIe3rxqoPMC1v+Zrd+WsjFzHWJLJNsiOg8QfpDS3oA5eSm7UKUZ5qhCbJv2pfA9negP8yokyOEPLMUTPXUDK2H4s3XT3YKPToE2+3fyvNVsGIYKTr+RXnBAH7HF7rr9CXkDP/JI6y8p9iPFvH2PRywAbdMJy9vfLzdfSJC6nRb7Q/JufyWukHM8qHQNVhnRRS18Z6frr/BEeTPSg8Qaiqqww1SBDUiF0jPqhrf9ShfVOxoTpFOuj7xw8LZPYN/UZYxD9ViRVV6RKXZlBOHQU+wMN7SZ9kV6/IgDEzKE5aiqfTihWLcPwbxxh7bvCx0gLkGqlwV4+Ru7Gh8GcqL+OabV32R33w7uLTTigCDUE=
    curibio_mantarray_ro: AgBoKVdJnwZ1vUdbxCBK1twYiuDs1jArVtuK49g1L/dK1SPoms30QAmRdOcgc8P2EvdWm8oN2zOI1tYKqOICxdEuuStbNwtrnCmsSKGqrj7e23DGzqzrrRhj8ENOWhibV8cMwppj5k6VLmU1hYypoKPe7/fOT06hPdTBjjaaREoX4kgx9mrEJxoRRtykrwAvn2kc70z3xPDu4pcWL9UoyHCZVZ5KMX5zpg+ln3t9nUUTiD+r/vgYRdWIyhhvRz1g1YqCESThef4Sub0kno8Zxk71yebResUqwGtgf6ohXoWFPIz7luhPTNx9J49N7Ld5C/+KMEHWIHIUqq3QZmrzg1uL1FXDgdZYgdZBXzjIJqgr7gUo4m7Qa5aXeOdAVWh4zR/s7APztfbm9B1bLFGGSFHjmGLIU+ZmbR5wMcBiMrVQD5gBeb0Z0oyd54QT7n7ztk1zUBUiVkwIMrDBaLW1hCwvA6+dHSUt1+vEX0AkC1iyFapqYW1P30WTH0SDLHw8nJ3eB7kOFzCd2ij8Q04OJfGOHWBCqJM3CizOa/d0NxJvOEWogvva0s/jBfNta+YOnnDMiGVl8iFQkQGAQ6n+esyN5PEP0PwkY6J6z+T77hjX56rpwZu33DmdsnXS/fVg4BaIH6ArYZ8cxNP6LjVIcTBFzFnhxnMQGkCG4zUgBmKUM+Eh/1R8SfZqhu0VuIfTjb4es7lCzsuJmKBol1S26LCSGzlaU9TpA4U=
  template:
    metadata:
      creationTimestamp: null
      name: curibio-mantarray-creds
      namespace: apiv2

