apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: curibio-users-creds
  namespace: apiv2
spec:
  encryptedData:
    curibio_users: AgCHX7bKOecB9WKOkjZcUkVkA1HYbpwXqSmwETH4cXcGFvNb9GBny3TpcMQrNXtz7vW+2oIdnBvSqwoa2dlN9Ha28IzsNeyIugzJgmWKSOkoAZmT16cpokY9oxW2SDoiZcDSoQHg/b0aPyGfve5HwgOqT6BG0A41Y2J6zGgAa4NTdf9Hkc5Fk79OCmI1KEbv7e0iUOh1il4xbVlozRn2kzHikqkCPaqMyfJk9Jim21x5fKmN4/9jGj2Gyp4fCDErL9iPSQee9b9u64oJ1Ixo61jSUKo7KPc5rsl6ljSMUI3YvXasUPwGxrrhSeyWkOUmx8903SvfwnuI4SuZQbhop/SFUvcWV5covQsP3F/VA0PS/oZrywFI5JCSAIZEKj73afGeBXCwyhaT/K0oHoTUgRg/D3P/7qZAMXB4EAnSfCuCn8EP+Lwa5Z8TEi7GFonW9hisdclxBmHxhNwPBoe3Zuv8++z9LzEj0Y0kJ1b/LF337QDdoYGZETWAgIm4cXVN00NmiTUg0h3SnOsEYGtiD7taHuEmFD3ch6eBCumv4umQhXd8CUpo6n9JA++latcAweX1Gz5xpStFknu7zZ8ni9AWf5Jra+vqU6cDo+hYK3dRubrdXBMWzw4jKVy8PnwQlCnkYp+KUhCVxSpzYkZdgKG6YXcOkkJD2ZqXUa4VKlmLNgIhvaAlzUN+eRS2+YsK2Kqr2vFHGbS6qKB9NQSh7JO9q3FAcS6vx5YZ
    curibio_users_ro: AgC3XgwCRwpRsSZy80/JXUXYKzZukqgAqcRrcJ5SpuQqHenYuN+q1WGAelFojtzPdHZqEVj2SgjssiKDQgEaKspy4Oh7WWhuNoRxanYt1ec5pgoq0PD0bpA0vuJxcrRaYSUONx+Fz3bh6o5q3Mv4aP8QA78HRccMa6d4oZfEQDyf0+V3M+kXdzTUUk1kHHIwNDpE7MFKAugRgK+TvPfruh+mRh6WTU1r9eLhD7qk4ueELEUYtcVwL9ObOLie5DnsCr/gPdpXgRIDgFCrunHlGZsoIvJDDhti2aZ6X2VEtb1qjV534vsVf7nK4aGF6soclHxy46HRMKDSMhVaWrW32WeVgGXmYl1zEGhxHYGTh3JFeOLsSWtRGOFtTJwt2LNW8YBmza0gQUuAACyhE5l48eI2OvrHa6Iv8XgZpqvDSk/XSCoGdmU79dp8hw2rmAF3KEgAjP9IQdF2k4PtfnFdkHY/iLAZRY94LCAsE4wESyiVNTDfqqrNzNuuLUe+siaql7B/hyIMRzB/PoezbCalURZfi640OqJgwStvgWgaIloSgSz+Nq73wgIX5tC0Y/2hpeAP+qYX0hDQQHcDN7hGsAJEeQBED8MyRh6qnQaAwrQysY59oPAuo65uaAlsijGCsMCYAdxLyEUKGictPlUKvfhXw3F/DlNqdJQo944vGzF7c8i5OjIKrLnuTaddMWMPe2+euBbVt4TXXxD/1DPZvYhnNn/A3TNfELcE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: curibio-users-creds
      namespace: apiv2

