apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: curibio-jwt-secret
  namespace: apiv2
spec:
  encryptedData:
    jwt-secret: AgAvo3/VXiV2j2jU0ePfHPaJHHV/tlGnkoJ70Gn2HJqlgZWXOCvHLRJtbPc/4Syb5Uueq9UxmlLXR7j67BihV5ddHrp80Mu1tCpPb4kdkqsqx+xth0Bf1SuImIYYjQQrAtSfbt3VmX3068g8dM0pcMFiJ6hZd6GAo0bKRcwbln3vHa/OcTqb5wO26kTByLKPOHMEsxOh8Gr6Td4zaCVNT233GfD/p5VMHYhNjG8NHNhS2jop/ztpN4MAKGtP3m2AVK16kK178QNVsyuCU3L0w3hPoSNA32vxSmyQuREUj0LPnkGtL9gOH1+ZCiEvGE2N+MG130BGGenlOUAwNV//I1Fx6iUHnEIOsVtMVwirftRZNyw4N/jM4Deq03HXK3QK07Df4e4dcizvUmiAmp9IigaQaauoiyKb1MpCdDu/3wguaNZeWfQ2zLbgjYzx/x7XRpcZynBagJeHvNS2dDM6z7Vg+lKBPN21ZCpBkytVTmANDIJsx8X6Jc66J0G2U5j7PQN0gG7iY+ZG+5LiJzY3UWtKp54Jb+GxP3pAgrS06YgFPk+xyImDGCyR3d94XqOVYRDB4WYzW0A8WP5ZqLWUOIMwjvY5KrDIUCQjv5uqp4tSbYYI2DccR1AEDAhDFvbwsYklGea1VuI6kKE+Pt5KfmI9ivCIak5MSw8u5NI5KxufCvwYxLJ1FF05apzy6g5SnF9s467plE9UQJaKE0TT/F2EaiQZUbkuccxE
  template:
    metadata:
      creationTimestamp: null
      name: curibio-jwt-secret
      namespace: apiv2

