apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd # only way to get card to appear in argocd
  finalizers: []
    # - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.52.4
    helm:
      values: |
        serviceAccount:
          create: false
          name: default
        promtail:
          serviceAccount:
            create: false
            name: default
        loki:
          serviceAccount:
            create: false
            name: default
          auth_enabled: false
          server:
            http_listen_port: 3100
          ingester:
            lifecycler:
              address: 127.0.0.1
              ring:
                kvstore:
                  store: inmemory
                replication_factor: 1
              final_sleep: 0s
            chunk_idle_period: 1h
            max_chunk_age: 1h
            chunk_target_size: 1048576
            chunk_retain_period: 30s
            max_transfer_retries: 0
          schema_config:
            configs:
              - from: 2020-10-24
                store: boltdb-shipper
                object_store: s3
                schema: v11
                index:
                  prefix: index_
                  period: 24h
          storage_config:
            boltdb_shipper:
              active_index_directory: /loki/index
              cache_location: /loki/index_cache
              cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
              shared_store: s3
            aws:
              s3forcepathstyle: true
              bucketnames: test-loki-logs
              region: us-east-2
          compactor:
            working_directory: /loki/compactor
            shared_store: s3
            compaction_interval: 5m
          limits_config:
            reject_old_samples: true
            reject_old_samples_max_age: 168h
            ingestion_rate_mb: 16
            ingestion_burst_size_mb: 32
          chunk_store_config:
            max_look_back_period: 0s
          table_manager:
            retention_deletes_enabled: false
            retention_period: 0s
          ruler:
            storage:
              type: s3
              s3:
                s3forcepathstyle: true
                bucketnames: test-loki-logs
                region: us-east-2

            rule_path: /loki/rules-temp
            alertmanager_url: http://localhost:9093
            ring:
              kvstore:
                store: inmemory
            enable_api: true

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
