apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki
resources:
- namespace.yaml

helmCharts:
  - name: grafana/loki
    releaseName: grafana-loki 
    repo: https://grafana.github.io/helm-charts
    # version: 4.6.0
    namespace: loki
