apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  source:
    chart:
    targetRevision: 2.5.9
    helm:
      values: |
        loki:
          auth_enabled: false

          schema_config:
            configs:
            - from: 2020-05-15
              store: boltdb-shipper
              object_store: s3
              schema: v11
              index:
                prefix: index_
                period: 24h

          storage_config:
            boltdb_shipper:
              active_index_directory: /loki/index
              cache_location: /loki/index_cache
              shared_store: s3

            aws:
              s3: s3://us-east-2/test-loki-logs
              s3forcepathstyle: true

        serviceAccount:
          create: false
          name: default
        promtail:
          serviceAccount:
            create: false
            name: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
