apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  source:
    chart: grafana-loki
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 2.5.9
    helm:
      values: |
        loki:
          auth_enabled: false
          schema_config:
            configs:
            - from: 2020-05-15
              store: aws
              object_store: s3
              schema: v11
              index:
                prefix: loki_
          storage:
            s3:
              endpoint: http://test-loki-logs.s3-website-us-east-2.amazonaws.com,
              region: us-east-2
              s3: s3://us-east-2/test-loki-logs
            type: s3
          storage_config:
            aws:
              s3: s3://us-east-2/test-loki-logs
        serviceAccount:
          create: false
          name: default
        promtail:
          serviceAccount:
            create: false
            name: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
