apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo
resources:
  - ../../base
  - templates/prod-build-container-template.yaml
  - templates/prod-run-terraform-template.yaml
  - prod_pr_merge_sensor.yaml
  - prod_pr_open_sensor.yaml
