apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo
resources:
  - ../../base
  - templates/build-container-template.yaml
  - templates/run-terraform-template.yaml
  - github_pr_merge_sensor.yaml
  - github_pr_open_sensor.yaml
