apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- curibio-operators-creds.yaml

patchesJson6902:
- target:
    kind: Deployment
    name: operators
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: "245339368379.dkr.ecr.us-east-2.amazonaws.com/jobs-operator:0.0.1"
    - op: add
      path: /spec/template/spec/containers/0/env/1/value
      value: "245339368379.dkr.ecr.us-east-2.amazonaws.com/queue-processor:0.0.1"