apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
namespace: argo

patchesJson6902:
  - target:
      version: v1
      kind: ServiceAccount
      name: argo-workflows-sa
    patch: |-
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::725604423866:role/workflow-pods-iam-role01
