apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: terraform-plan-template
  namespace: argo
spec:
  serviceAccountName: argo-workflows-sa
  templates:
    - name: run-terraform-plan
      script:
        image: 725604423866.dkr.ecr.us-east-2.amazonaws.com/builder
        source: |
          echo "Changes found in {{inputs.parameters.path}}"

          cd {{inputs.parameters.path}}
          terraform init -backend-config=backend/modl_env_config.tfvars

          PLAN_OUTPUT=$(terraform plan -var-file=modl_env.tfvars -no-color)
          builder --pr-number={{inputs.parameters.number}} --pr-comment="PLAN FOR: {{inputs.parameters.path}} <br /> $PLAN_OUTPUT"

---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: terraform-apply-template
  namespace: argo
spec:
  serviceAccountName: argo-workflows-sa
  templates:
    - name: run-terraform-apply
      script:
        image: 725604423866.dkr.ecr.us-east-2.amazonaws.com/builder
        source: |
          echo "Applying changes found in {{inputs.parameters.path}}"

          cd {{inputs.parameters.path}}

          terraform init -backend-config=backend/modl_env_config.tfvars
          terraform apply -auto-approve -var-file=modl_env.tfvars -no-color
