apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-pr-merge
  namespace: argo
spec:
  serviceAccountName: argo-workflows-sa
  template:
    nodeSelector:
      group: argo
  dependencies:
    - name: github-dep
      eventSourceName: github
      eventName: k8s_curi
      filters:
        data:
          # Name of the event that triggered the delivery: [pull_request, push, ...]
          # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads
          - path: body.X-GitHub-Event
            type: string
            value:
              - pull_request
          - path: body.action
            type: string
            value:
              - closed
          - path: body.pull_request.merged
            type: bool
            value:
              - "true"
          - path: body.pull_request.base.ref
            type: string
            value:
              - modl-qc
