apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system
resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::725604423866:role/eks-cluster-autoscaler
    target:
      kind: ServiceAccount
      name: cluster-autoscaler
      namespace: kube-system
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/command/8
        value: --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/modl-v2
    target:
      kind: Deployment
      name: cluster-autoscaler
      namespace: kube-system
