bucket               = "curi-eks-prod-cluster-tf-state"
key                  = "prod/db_viewer/services/db_viewer.tfstate"
region               = "us-east-2"
dynamodb_table       = ""
workspace_key_prefix = "env"
