apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/externalName
      value: prod-curibio.cluster-ceyftucdpgdc.us-east-2.rds.amazonaws.com
  target:
    kind: Service
    name: psql-rds
    version: v1
