import os

PHENO_BUCKET = "phenolearn"

TRAIN_ARCH = "resnet18"
TRAIN_PRECROP_SIZE = 224
TRAIN_EPOCHS = 5
TRAIN_BATCH_SIZE = 32
TRAIN_LEARNING_RATE = 0.1
TRAIN_MOMENTUM = 0.9
TRAIN_WEIGHT_DECAY = 0.0001
TRAIN_CHECKPOINT = None
TRAIN_TRANSFER = True
TRAIN_AUGMENT = True
TRAIN_PREAUGMENT = False
TRAIN_STOP = "epochs"
TRAIN_NO_SCALE = True
TRAIN_CONVERT_TO_GRAY = False
TRAIN_WEIGHTED_SAMPLING = True
TRAIN_NUM_WORKERS = 2
TRAIN_MODE = "categorical"
TRAIN_REG_WEIGHT = 10.0
TRAIN_CPU = True


# ------------------------------> Queries

SELECT_QUERY = """SELECT * FROM job_queue LIMIT 1 FOR UPDATE SKIP LOCKED;"""
UPDATE_QUERY = """UPDATE job_queue SET status=(%s) where id=(%s);"""
