apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- namespace.yaml
- argocd_v2.2.5.yaml
#- https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.5/manifests/install.yaml
