apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.7/manifests/install.yaml

patchesJson6902:
- target:
    kind: ConfigMap
    name: argocd-cm
  patch: |-
    - op: add
      path: /data
      value:
        resource.customizations.health.networking.k8s.io_Ingress: "hs = {}\nhs.status = \"Healthy\"\nreturn hs\n"

