apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  labels:
    grafana_dashboard: "1"
data:
  login-attempts.json: |-
    {{- $.Files.Get "dashboards/login-attempts.json"  | nindent 6 -}}
