apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  labels:
    grafana_dashboard: "1"
data:
  login-attempts.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 1,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "loki"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "options": {
            "displayMode": "basic",
            "minVizHeight": 10,
            "minVizWidth": 0,
            "orientation": "vertical",
            "reduceOptions": {
              "calcs": ["count"],
              "fields": "",
              "values": false
            },
            "showUnfilled": true,
            "valueMode": "color"
          },
          "pluginVersion": "10.1.5",
          "targets": [
            {
              "datasource": {
                "type": "loki"
              },
              "editorMode": "builder",
              "expr": "sum by(customer_id, user_id) (count by(customer_id, user_id) (rate({container=\"users\"} |= `user_id` | json | status_code = `200` | method = `POST` [$__interval])))",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Successful User Login Attempts",
          "type": "bargauge"
        },
        {
          "datasource": {
            "type": "loki"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "continuous-reds"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 0
          },
          "id": 2,
          "options": {
            "displayMode": "basic",
            "minVizHeight": 10,
            "minVizWidth": 0,
            "orientation": "vertical",
            "reduceOptions": {
              "calcs": ["count"],
              "fields": "",
              "values": false
            },
            "showUnfilled": true,
            "valueMode": "color"
          },
          "pluginVersion": "10.1.5",
          "targets": [
            {
              "datasource": {
                "type": "loki"
              },
              "editorMode": "builder",
              "expr": "sum by(customer_id, user_id) (count by(customer_id, user_id) (rate({container=\"users\"} |= `user_id` | json | status_code = `401` | method = `POST` [$__interval])))",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Failed User Login Attempts",
          "type": "bargauge"
        },
        {
          "datasource": {
            "type": "loki"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 8
          },
          "id": 3,
          "options": {
            "displayMode": "basic",
            "minVizHeight": 10,
            "minVizWidth": 0,
            "orientation": "vertical",
            "reduceOptions": {
              "calcs": ["count"],
              "fields": "",
              "values": false
            },
            "showUnfilled": true,
            "valueMode": "color"
          },
          "pluginVersion": "10.1.5",
          "targets": [
            {
              "datasource": {
                "type": "loki"
              },
              "editorMode": "builder",
              "expr": "sum by(customer_id) (count by(customer_id) (rate({container=\"users\"} != `user_id` | json | status_code = `200` | method = `POST` [$__interval])))",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Successful Admin Login Attempts",
          "type": "bargauge"
        },
        {
          "datasource": {
            "type": "loki"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "continuous-reds"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 8
          },
          "id": 4,
          "options": {
            "displayMode": "basic",
            "minVizHeight": 10,
            "minVizWidth": 0,
            "orientation": "vertical",
            "reduceOptions": {
              "calcs": ["count"],
              "fields": "",
              "values": false
            },
            "showUnfilled": true,
            "valueMode": "color"
          },
          "pluginVersion": "10.1.5",
          "targets": [
            {
              "datasource": {
                "type": "loki"
              },
              "editorMode": "builder",
              "expr": "sum by(customer_id) (count by(customer_id) (rate({container=\"users\"} != `user_id` | json | status_code = `401` | method = `POST` [$__interval])))",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Failed Admin Login Attempts",
          "type": "bargauge"
        }
      ],
      "refresh": "",
      "schemaVersion": 38,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-7d",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Login Attempts",
      "uid": "a7c0828a-dadc-467a-959c-77a320d79bbc",
      "version": 1,
      "weekStart": ""
    }
  login-attempts-2.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 1,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "loki"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "options": {
            "displayMode": "basic",
            "minVizHeight": 10,
            "minVizWidth": 0,
            "orientation": "vertical",
            "reduceOptions": {
              "calcs": ["count"],
              "fields": "",
              "values": false
            },
            "showUnfilled": true,
            "valueMode": "color"
          },
          "pluginVersion": "10.1.5",
          "targets": [
            {
              "datasource": {
                "type": "loki"
              },
              "editorMode": "builder",
              "expr": "sum by(customer_id, user_id) (count by(customer_id, user_id) (rate({container=\"users\"} |= `user_id` | json | status_code = `200` | method = `POST` [$__interval])))",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Successful User Login Attempts",
          "type": "bargauge"
        },
        {
          "datasource": {
            "type": "loki"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "continuous-reds"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 0
          },
          "id": 2,
          "options": {
            "displayMode": "basic",
            "minVizHeight": 10,
            "minVizWidth": 0,
            "orientation": "vertical",
            "reduceOptions": {
              "calcs": ["count"],
              "fields": "",
              "values": false
            },
            "showUnfilled": true,
            "valueMode": "color"
          },
          "pluginVersion": "10.1.5",
          "targets": [
            {
              "datasource": {
                "type": "loki"
              },
              "editorMode": "builder",
              "expr": "sum by(customer_id, user_id) (count by(customer_id, user_id) (rate({container=\"users\"} |= `user_id` | json | status_code = `401` | method = `POST` [$__interval])))",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Failed User Login Attempts",
          "type": "bargauge"
        },
        {
          "datasource": {
            "type": "loki"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 8
          },
          "id": 3,
          "options": {
            "displayMode": "basic",
            "minVizHeight": 10,
            "minVizWidth": 0,
            "orientation": "vertical",
            "reduceOptions": {
              "calcs": ["count"],
              "fields": "",
              "values": false
            },
            "showUnfilled": true,
            "valueMode": "color"
          },
          "pluginVersion": "10.1.5",
          "targets": [
            {
              "datasource": {
                "type": "loki"
              },
              "editorMode": "builder",
              "expr": "sum by(customer_id) (count by(customer_id) (rate({container=\"users\"} != `user_id` | json | status_code = `200` | method = `POST` [$__interval])))",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Successful Admin Login Attempts",
          "type": "bargauge"
        },
        {
          "datasource": {
            "type": "loki"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "continuous-reds"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 8
          },
          "id": 4,
          "options": {
            "displayMode": "basic",
            "minVizHeight": 10,
            "minVizWidth": 0,
            "orientation": "vertical",
            "reduceOptions": {
              "calcs": ["count"],
              "fields": "",
              "values": false
            },
            "showUnfilled": true,
            "valueMode": "color"
          },
          "pluginVersion": "10.1.5",
          "targets": [
            {
              "datasource": {
                "type": "loki"
              },
              "editorMode": "builder",
              "expr": "sum by(customer_id) (count by(customer_id) (rate({container=\"users\"} != `user_id` | json | status_code = `401` | method = `POST` [$__interval])))",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Failed Admin Login Attempts",
          "type": "bargauge"
        }
      ],
      "refresh": "",
      "schemaVersion": 38,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-7d",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Login Attempts-2",
      "uid": "a7c0828a-dadc-467a-959c-77a320d79bbc",
      "version": 1,
      "weekStart": ""
    }
