apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    path: cluster/manifests/sealed-secrets
    repoURL: https://github.com/CuriBio/k8s_curi.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
