---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-credentials
  namespace: argocd
stringData:
  GRAFANA_CLOUD_INSTANCE_TOKEN: glsa_6dx8INmoURqdKp35wJSxOuanBZCqkE3K_c4f51c51
type: Opaque

# ---
# apiVersion: grafana.integreatly.org/v1beta1
# kind: Grafana
# metadata:
#   name: grafana
#   namespace: argocd
#   labels:
#     dashboards: grafana
# spec:
#   external:
#     url: https://grafana.grafana.net/
#     apiKey:
#       name: grafana-cloud-credentials
#       key: GRAFANA_CLOUD_INSTANCE_TOKEN

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: grafanadashboard-sample
  namespace: argocd
spec:
  resyncPeriod: 30s
  instanceSelector:
    matchLabels:
      dashboards: grafana
  json: >
    {
    "id": null,
    "title": "Simple Dashboard",
    "tags": [],
    "style": "dark",
    "timezone": "browser",
    "editable": true,
    "hideControls": false,
    "graphTooltip": 1,
    "panels": [],
    "time": {
        "from": "now-6h",
        "to": "now"
    },
    "timepicker": {
        "time_options": [],
        "refresh_intervals": []
    },
    "templating": {
        "list": []
    },
    "annotations": {
        "list": []
    },
    "refresh": "5s",
    "schemaVersion": 17,
    "version": 0,
    "links": []
    }

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: dashboard-definition
#   namespace: <grafana-operator-namespace>
# spec:
#   resyncPeriod: 30s
#   instanceSelector:
#     matchLabels:
#       dashboards: <Grafana-cloud-stack-name>
#   json: >
#     {
#     "id": null,
#     "title": "Simple Dashboard from ConfigMap",
#     "tags": [],
#     "style": "dark",
#     "timezone": "browser",
#     "editable": true,
#     "hideControls": false,
#     "graphTooltip": 1,
#     "panels": [],
#     "time": {
#         "from": "now-6h",
#         "to": "now"
#     },
#     "timepicker": {
#         "time_options": [],
#         "refresh_intervals": []
#     },
#     "templating": {
#         "list": []
#     },
#     "annotations": {
#         "list": []
#     },
#     "refresh": "5s",
#     "schemaVersion": 17,
#     "version": 0,
#     "links": []
#     }

# ---
# apiVersion: grafana.integreatly.org/v1beta1
# kind: GrafanaDashboard
# metadata:
#   name: grafanadashboard-from-configmap
#   namespace: argocd
# spec:
#   instanceSelector:
#     matchLabels:
#       dashboards: grafana
#   configMapRef:
#     name: dashboard-definition
#     key: json
