bucket               = "curi-eks-test-cluster-tf-state"
key                  = "test/advanced-analysis/advanced-analysis-api.tfstate"
region               = "us-east-2"
dynamodb_table       = ""
workspace_key_prefix = "env"
