{
 "title": "Pulse3D Stats",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Uploads per month per customer",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT to_char(date_trunc('month', created_at), 'YY/MM') AS month_created, customer_id, count(*) FROM uploads WHERE created_at >= '${__from:date:YYYY-MM-DD HH:mm:ss}' AND created_at <= '${__to:date:YYYY-MM-DD HH:mm:ss}' GROUP BY month_created, customer_id ORDER BY month_created, customer_id;"
    }
   ]
  },
  {
   "title": "Analyses per month per customer",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT to_char(date_trunc('month', created_at), 'YY/MM') AS month_created, customer_id, count(*) FROM jobs_result WHERE created_at >= '${__from:date:YYYY-MM-DD HH:mm:ss}' AND created_at <= '${__to:date:YYYY-MM-DD HH:mm:ss}' GROUP BY month_created, customer_id ORDER BY month_created, customer_id;"
    }
   ]
  },
  {
   "title": "Monthly active vs. inactive customers",
   "type": "barchart",
   "description": "Customers are considered active in a given month if they ran at least 1 analysis. Deactivated users are not removed",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select total_active_per_month.month, total_active, (sum(num_registrations) over(order by coalesce(total_active_per_month.month, total_registrations_per_month.month))) - total_active as total_inactive from ( select to_char(date_trunc('month', created_at), 'YY/MM') as month, count(*) as num_registrations from customers group by month order by month desc) total_registrations_per_month full outer join (select to_char(date_trunc('month', created_at), 'YY/MM') as month, count(distinct customer_id) as total_active from jobs_result group by month order by month) total_active_per_month ON total_registrations_per_month.month=total_active_per_month.month;\n"
    }
   ]
  },
  {
   "title": "Total number of uploads",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT count(*) as total_uploads from uploads WHERE created_at >= '${__from:date:YYYY-MM-DD HH:mm:ss}' AND created_at <= '${__to:date:YYYY-MM-DD HH:mm:ss}'"
    }
   ]
  },
  {
   "title": "Total number of jobs",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS total_jobs FROM jobs_result WHERE created_at >= '${__from:date:YYYY-MM-DD HH:mm:ss}' AND created_at <= '${__to:date:YYYY-MM-DD HH:mm:ss}'"
    }
   ]
  },
  {
   "title": "Total number of uploads by non-Curi users",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS total_uploads FROM uploads u JOIN customers c ON c.id=u.customer_id WHERE c.email NOT LIKE '%curibio.com' AND u.created_at >= '${__from:date:YYYY-MM-DD HH:mm:ss}' AND u.created_at <= '${__to:date:YYYY-MM-DD HH:mm:ss}'"
    }
   ]
  },
  {
   "title": "Total number of jobs by non-Curi users",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS total_jobs FROM jobs_result j JOIN customers c ON c.id=j.customer_id WHERE c.email NOT LIKE '%curibio.com' AND j.created_at >= '${__from:date:YYYY-MM-DD HH:mm:ss}' AND j.created_at <= '${__to:date:YYYY-MM-DD HH:mm:ss}'"
    }
   ]
  },
  {
   "title": "Total number of jobs per Pulse3D version",
   "type": "table",
   "gridPos": { "h": 14, "w": 5, "x": 19, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT meta->'version' AS p3d_version, count(*) AS total_jobs FROM jobs_result WHERE created_at >= '${__from:date:YYYY-MM-DD HH:mm:ss}' AND created_at <= '${__to:date:YYYY-MM-DD HH:mm:ss}' GROUP BY 1 ORDER BY 1 DESC;"
    }
   ]
  },
  {
   "title": "Total number of uploads per product type",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT type, count(*) AS total_uploads FROM uploads WHERE created_at >= '${__from:date:YYYY-MM-DD HH:mm:ss}' AND created_at <= '${__to:date:YYYY-MM-DD HH:mm:ss}' GROUP BY 1;"
    }
   ]
  },
  {
   "title": "Average Pulse3D Queue + Analysis Duration per Upload Type",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT type, AVG(extract(epoch FROM finished_at - created_at) / 60) AS avg_minutes FROM jobs_result WHERE created_at >= '${__from:date:YYYY-MM-DD HH:mm:ss}' AND created_at <= '${__to:date:YYYY-MM-DD HH:mm:ss}' GROUP BY type;"
    }
   ]
  },
  {
   "title": "Current Pulse3D Queue Length by version",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT queue, count(*) FROM jobs_queue GROUP BY queue;"
    }
   ]
  },
  {
   "title": "Total number of jobs per product type",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT type, count(*) AS total_jobs FROM jobs_result WHERE created_at >= '${__from:date:YYYY-MM-DD HH:mm:ss}' AND created_at <= '${__to:date:YYYY-MM-DD HH:mm:ss}' GROUP BY 1;"
    }
   ]
  },
  {
   "title": "Average Pulse3D Analysis Duration per Upload Type",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT type, AVG(extract(epoch FROM finished_at - started_at) / 60) AS avg_minutes FROM jobs_result WHERE created_at >= '${__from:date:YYYY-MM-DD HH:mm:ss}' AND created_at <= '${__to:date:YYYY-MM-DD HH:mm:ss}' GROUP BY type;"
    }
   ]
  },
  {
   "title": "Total number of jobs per product type per customer",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT j.customer_id, j.type, count(*) AS total_jobs FROM jobs_result j JOIN uploads u ON j.upload_id = u.id WHERE j.created_at >= '${__from:date:YYYY-MM-DD HH:mm:ss}' AND j.created_at <= '${__to:date:YYYY-MM-DD HH:mm:ss}' GROUP BY 1, 2 ORDER BY customer_id;"
    }
   ]
  },
  {
   "title": "Total number of uploads per product type per customer",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT customer_id, type, count(*) AS total_uploads FROM uploads WHERE created_at >= '${__from:date:YYYY-MM-DD HH:mm:ss}' AND created_at <= '${__to:date:YYYY-MM-DD HH:mm:ss}' GROUP BY 1, 2 ORDER BY customer_id;"
    }
   ]
  },
  {
   "title": "Total number of job failures per product type per customer",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT j.customer_id, j.type, count(*) AS total_failures FROM jobs_result j JOIN uploads u ON j.upload_id = u.id WHERE j.meta->'error' IS NOT NULL AND j.created_at >= '${__from:date:YYYY-MM-DD HH:mm:ss}' AND j.created_at <= '${__to:date:YYYY-MM-DD HH:mm:ss}' GROUP BY 1, 2 ORDER BY customer_id;"
    }
   ]
  },
  {
   "title": "Total number of job failures per product type per upload",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT customer_id, upload_id, type, count(*) FROM jobs_result WHERE meta->'error' IS NOT NULL AND created_at >= '${__from:date:YYYY-MM-DD HH:mm:ss}' AND created_at <= '${__to:date:YYYY-MM-DD HH:mm:ss}' GROUP BY 1, 2, 3 ORDER BY 4 DESC;"
    }
   ]
  }
 ]
}