{
 "title": "Service Stats",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total 400s by Service",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"users\"} |= `status_code` | json | status_code >= 400 | status_code < 500 [$__range]))",
     "legendFormat": "users"
    },
    {
     "expr": "sum(count_over_time({container=\"pulse3d\"} |= `status_code` | json | status_code >= 400 | status_code < 500 [$__range]))",
     "legendFormat": "p3d"
    },
    {
     "expr": "sum(count_over_time({container=\"mantarray\"} |= `status_code` | json | status_code >= 400 | status_code < 500 [$__range]))",
     "legendFormat": "mantarray"
    }
   ]
  },
  {
   "title": "Total 500s by Service",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"users\"} |= `status_code` | json | status_code >= 500 [$__range]))",
     "legendFormat": "users"
    },
    {
     "expr": "sum(count_over_time({container=\"pulse3d\"} |= `status_code` | json | status_code >= 500 [$__range]))",
     "legendFormat": "p3d"
    },
    {
     "expr": "sum(count_over_time({container=\"mantarray\"} |= `status_code` | json | status_code >= 500 [$__range]))",
     "legendFormat": "mantarray"
    }
   ]
  },
  {
   "title": "Total Errors by Service",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"users\"} |= `exception` | json [$__range]))",
     "legendFormat": "users"
    },
    {
     "expr": "sum(count_over_time({container=\"pulse3d\"} |= `exception` | json [$__range]))",
     "legendFormat": "p3d"
    },
    {
     "expr": "sum(count_over_time({container=\"mantarray\"} |= `exception` | json [$__range]))",
     "legendFormat": "mantarray"
    }
   ]
  },
  {
   "title": "Response Codes in nginx-ingress",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"nginx-ingress\"} |~ `\" 1\\d\\d ` [$__range]))",
     "legendFormat": "100s"
    },
    {
     "expr": "sum(count_over_time({container=\"nginx-ingress\"} |~ `\" 2\\d\\d ` [$__range]))",
     "legendFormat": "200s"
    },
    {
     "expr": "sum(count_over_time({container=\"nginx-ingress\"} |~ `\" 3\\d\\d ` [$__range]))",
     "legendFormat": "300s"
    },
    {
     "expr": "sum(count_over_time({container=\"nginx-ingress\"} |~ `\" 4\\d\\d ` [$__range]))",
     "legendFormat": "400s"
    },
    {
     "expr": "sum(count_over_time({container=\"nginx-ingress\"} |~ `\" 5\\d\\d ` [$__range]))",
     "legendFormat": "500s"
    }
   ]
  }
 ]
}