apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: job_runner.test
spec:
  scope: Namespaced
  group: test
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                jobqueue:
                  type: string
  names:
    kind: JobRunner
    plural: jobrunners
    singular: jobrunner
    shortNames:
      - sk
      - sks
