apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobrunners.curibio.dev
  finalizers:
spec:
  scope: Namespaced
  group: curibio.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                job_queue:
                  type: string
                ecr_repo:
                  type: string
                max_num_of_workers:
                  type: integer
                product_specific:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true

  names:
    kind: JobRunner
    plural: jobrunners
    singular: jobrunner
    shortNames:
      - jr
      - jrs
