---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: argo
spec:
  encryptedData:
    aws_access_key_id: AgBxjC0Ud7WmZA7SIeULNXUFiXFWqvsmCTNaAvFECyEQHQcFXk77QHTpDIHDtjtACmRjTyObVzOdCemsFlAcAJJQONmbE0GK5qp8dmrZJ3TLcrrC/DNzS+KiwDKdAON3ZXSu6M8vXuuTQxX8mi7cgG5w9XZ4sTQfWVCDOaG1Bp37NtOoOi5HEgj636+9yJ0TqwsjfjB1V+Dd3vpX8x5MVhP/Ajs4P8QE/wjLgIhNwYQIEacGoRHG6ViNUmTqolVDRNDdElkqSHGtI4LFOwMYe3FccZ89qQ1TIfSEhiPH75JbUiqfcCgx/pZwgGdnd3I8BKxwEv6cSGTaLJinsPiTXNoB6pXYXrphmqG1JPXAFOEvZy2CUVYnyb3xu0aRYRFknmbmDYp/dU+xIaXgag5m8vCz4zss28eXNw+94+qQDzv4+3M3GN58cmOlkf5O0WHiTB2/RvEx/UsVpSN+k+DzKqKm4+x+7gRDndIJdpOcZJFUd65a2jMx9krnhzhkqAeEogAHiLJIx8DwZdjZQ34IQ3Sk8ixjvWtDsDPz6dLO/KrLJqnjl8CHE9vIF8+U0yNQ0QJrsaiuw7WUmzeUcx6kfx9WY4B0Qbsrx5rttKFWDeOGAdeNsmv10oZvBWngxTe4iWl2Q0TYJ0HJwQ1ZxxajNMGTNLYSc7nSbPEE0cjXnU4ZsznaYYg1Cj4bt1bVMd8Uk3ti4ZoqfVN2g3DYuG/uWT9pA2g8IQ==
    aws_secret_access_key: AgCW2388QDM2Nc3MpBLRdZbR5pVMaUFceLD/3PK9Z3T2AsfMtkUdlP5d8z98kMqyZmBjiO3z5PS4zwkmuUsHpnUc0I4EHpabim1lNE6btwHfUSo0joHGFEWsYrxUOx+ZMFI1oldjpyGL3itW2Jie7SsX9+Zxg4DPz2V+//hC0CNn248SHXgV2APx3q5zMlwWovgCk+rqxLk7Tmyf8KWrGb6xhgUiDlYoB2rlYB26KppLLpWXdXy9J6aHzKlSEfuSI9E8ldfBU2aKsB6x+SdaoQiHwzn4888GLEb/iB+j10bZORSImCth3AVDBn8O9VXRg44SUkB0BICTazCymw0hB8HNDBehNILHCfdoO7wy5zZbJkMYzksAbVF3CIeKfNhIIEJNgKS8FhGSYPVQg4ck8B3Z/Gd4YWs0rp02HPD/I/KzSwAlfeoAGEnOBRg5UG5CdU4bNFSuEV+QFDLMGOVVX0XifA241fWqZDc03e4EcTEP2DRzU7iWgyg7WOgRDXvUKFlsem+YblIDuA4Ea6OuWDujVbolQHZthfPIIZer6Xjqsp0putQcn0g+cl2IDhDUrwvfMjdQxaDZm9rb/OveOvyJaPbpqfSIFohQi5iuWl0WqPztw6gNpJWTAEZIVVs615OqYjq9ybdT9TUxEpIv1m0i2efYlCmd2BjUMQO+bWZsqdwmYRugWwbLM9SlToREEReo5lQf1Cf9k+gG1M+le4cBGLfyKnfzjLu8dv14xMFIl9BXf2ohH8iN
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: argo
