apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access-token
  namespace: argo
spec:
  encryptedData:
    token: AgBGtR+FwrW0A7W2U6ASiVCkr8Us5Q1t1hR+4pirLfLz/QkAoV4QFj7/O/Rw4Y6Hu9t4rkpcVf/H0DY9zVFqdWDF+xg5tt+7dI9shZVP5MAoK6ywwTDko+bSFtY9zIUSFMCumoHsFNNgUn9DyPC+G7pd9wUwH31INqj7l6WYN0oecHvtibUR0oKcnedvHjSMKWH/g4xmD2ajTc7xqZcJBHC8DxoiukcuA6O2nqA1XDSHG2Zb5vtxNAQK1zUOI6wkRort6ZoAD3h2R9gQeyao8V89GiE0Z7Jf9dQoBbf60ic7aY3HOP5qHhvlNQb0sJVcXlxDsIM4UDNfP4Hyb3Cbl1emnI9clmRQ0aVHVakCvrYQ1652ed+6NY8+0ruB+sJsMhAvxpe9rMe7iNiTTLDaBMOZNw8LymTLuQ/DKfbYkQT0D/IuJqPckPm4VN0VbRN1SQkely6ca+IMD6MNKsb1+rf/Ea+60xekzg60y7p+CSEbZOhLKu3wgsbw/v/pU28FE7xjarnguLb+feSl35yPVjPPEJiGgt0m8MmLjUWTuF5FrQ3DYuDYCB2PP5eIIckd+lwTAeHYZNy4kuOFUWoE+KItSyiYE3zflHDrPnCVFkUSvqX/cE46WRJTRNeTmp+j1dWZHhUfsg4dqXLccYaJnT/rjerZCQmc6Uky6Vtcp1vl0Ptzr3QtON8afgouypvSpNzN/EyxYhFubzvNdZ5m0ZBUOzPZYjIXbL36Tx6W2cEWMFE7IOUM3WX3
  template:
    metadata:
      creationTimestamp: null
      name: github-access-token
      namespace: argo

