apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret
  namespace: argo
spec:
  encryptedData:
    token: AgABHmzNkii6wAf9mzR87QXiUDMfiqwx+1uNpecZw8+AvBOJbFHV9NAiCM5gPDstxrpZC+Mbcem8FC0KJ4DjnWVPPFzDU3EtWtpRzy1bxbLxk/npPzFlK3Q7WFVXqZm4aLSJJhf7EwerRCMxwNoRH2I0iVj0hr5y1fBHEaA+cfMvveTRFDxOTrvS3VDL5c9D4hDO1mB6enbVyM3e6HyOfqEAJJeIAke6gkNT1r2MLmtD2ANAr7pxYH/9eI6AiH/gEPs2ATiKMY6tnwPK68eGOW95SgMc+WQNpr/STtfy71FW5MIM6YO9Tt7RK3wWP04EMdLXDsGP09wKjL0SjtmZcNN/6e5wxFa5uGDkH6lLzfgaxlOBgcDE6BfuvVWJ5UMiSwCLgC9jpC+8xnsxBWrYBhrHRNEg/sSDQJxrMGzsQlmPg1s0vUoY+aWxjYI0bp3eIklwzPfkearUDq1pW2WzTMvxlmEw9D7LqJAUzKQBCUzBekRXtrBJ20pEnMLykWkfTzVXntgBxV3mvxsblfq2qI0L8UF8bewwT1IQ6oqMdrmOQMxbP5+c4XjXJxdk0qPa4pqYL1jO75HzeR/mr3i7JxPZ3dr+7oc298L2xXtCKsVRF0ZjlpTfl/dXfEtJtfpOUWtrt6OeMMxHrLX2PDxH65rsPqLAfagWKGK6vLoV/B+5w8OhaVHVvjXiX4cY5GgkREjgUR+3YbHDq1tbDleACstGkC/MFBS1XrMO/q/ge4HccDuudjcPiFFF
  template:
    metadata:
      creationTimestamp: null
      name: github-webhook-secret
      namespace: argo
