apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access-token
  namespace: argo
spec:
  encryptedData:
    token: AgA/KlqBUit9lG6LFJyOKfs3Xg53rIlvodXPXPZTq7rNPgZgLi08xR77aFXSNsf6eyG39moAgYnlo9wlD4qb2viP216x8CCWXfM1BopNslg+SE5K0wD4KZet9GhUoy8JT4nTcMn0Jk8HHgA4w2rI+yT5NcLtCEOEyjwcVcD+o85lrKSAltLFRAJBw0rEbh2gQ0mseHS3JVYG0jxnwzIZggdXoHx2gzeboOFH4OHnS/gGYbiosfLt7Bzb9sVIJHtunvPJzGXRcL/6KFPC4o05oiDGkPIsyV5DJJG2Zaug7AZNjswuNTmcuOjYsIATkv2ga+4QeL0dBwoO/gUA4aRMuV5sj6gelEizKWpullW+/uw7oGPsqV3Wdxpy1sY2UoC09FPX94/Q7qj6tdQpfN0rqVAAOZjEiQGRLVXP+pYR9wYEIEg/p5C+ECEfZo0J/mwe1fpzOLqR1cLlKR7En/pp2YzIh09uM7A1hqhtrbky8jr3f1oOO7cLVY8iJpexXjZorXJIfakzaK2PKYN2s49aoB+f84E5U+/06dYl26jUXZo+go1+ZqUQPIplgOJooH+b9Fbk12bZm9bFmYzU4w8M/4OKopDObhGylwAAaB6eLVlnjLn04b2mhhUijIcvzjAtBORakxDAWouCpqLZh3vS096SGbnZHEwWVAyhOEzExi+gTQSuw3MCHUcsGAdThxaqZwhAT/ylBB/E3c7G2KDXPU6fMiM0ywy5g6Bwqyc6a+FQHdWFV2CdJOBLtg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access-token
      namespace: argo

