apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access-token
  namespace: argo
spec:
  encryptedData:
    token: AgAthUqosL2jYNPje4/TSqCWRHftmXlAX6/LgFFpLmKbgy3dRfQF5CHLaVLVfpYY+Bs9VmkLejZPFd3cP6T4+n5rwUFxl8E21bL3IVbmlXxFXxIjbYElDmclaX86XAPE0RB/iwqHtxpqpTTPdMvywlDLjw7hmJGD755aGytaskJEgB23yQAHrOOpxMuaV3oM1EdqACOq16PAEQVNTiQz2tkD43mZgBm16h7ZqLDeQb6I+//OaaHCigo9CtNl4GNP6hVdcoEYVrw/2EBKeUDasnGAHdPl90SL1S58K6Pzo4rUDiBUHmYw5UCogA28HckFl/P3eYm5A8MGoP7lMeSia/bMIDk5faKeAtmw3+x4us2SCzywnGlPJ/V3Sof8EYnfMOayOjDR09JKPYB9vuQj8VMcxOuIxQnd1WLs1+0n8ndiDdr2C79ThQzEFvb4JJl0docjP2+6IBf87/379RxzfVzga86zY+klHNe4DuUFob/cwR5178LwbDiNN3ikR5lnWE0qm06BaUM5sCfPEu/f96mPrCDY820QaphLM5e/JoFRfSc7sEHRZDmdEPo5+etQq1vDDGN+kQgDYvQeNEGGB4cIrWPymviDVL0ANkZmekLq5aQYWX/FwD1AUO+U6ramz7FodzHyriQm2Vuq7T6yj5Vf2qXGOVJTCcEoTYWlzS5/b4PAvv1hVccFCo0dKql8ATTmofLoNkYiaxgqay/bgGCYRp7lE3p24YqZADBjpsSkOo29Mlz0GqX3
  template:
    metadata:
      creationTimestamp: null
      name: github-access-token
      namespace: argo

