apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access-token
  namespace: argo
spec:
  encryptedData:
    token: AgCaJszF5fIz2tQVI02Cy01Y5qbgv3ZNnZhrBrKps0ew7BHJCsLAZxo1/qrg93Cg6ACpjAGjPFyZEeSJS2BBcbGgoFG7+g2+iAxPn2ytyo7/PLYnk7bHxYGOKoai0TqSLb9vWwCMPz3jCeMjQ8rjKgxhUqMUtzLS7w/31mMnZklwhO1+s902yri/Ul6+4mqlRMgh+4expypOvDxJBtYrE1pUSVHTBTzchJ7HeCkNCV7wn+HM5BtkkJKBnKnly/cY/GKs5vPf3ed1bIUwby9fW62PN6qubLq9OEGkLljlvyFdE3FZbtv49iBGiZPjZa22wJjdBS/f/8+tLsg9ncPFGlHaLpe+bd5+JEELZ7t2yfPf6LPIVStFvd8ZoIzguN8EskIearM7/q4zeKSxVyrDyqqA3+g22TsRRWFNiJzP5D3dp2ZiO3FzkuJlBzi+R5cNDKdWGcZDi6xKfFPgRyFJv40anhgEKJX0pcq5OBpjjZJS/u2zpUiq9PiGVKycqlWXzXJCTjpbCywAKg8CCDXeF1KKxd8DxVGyWVJBbIVmlA6BmK6LodNufQquyuxqa4adZZ7lt1oDxcwpgKia4T7EtE5mwEBM+4cmE59dy6ksPV6LWg7yg9zfEiotVImcrXa8jy7ROFFh/0/uwhro/7z0CDPEaZ8YV3EQ3QTSWjj+uIlxphDPanwa92j+JpAu9glNntNTNZ3k5UOGbiDCynrNufKejMVUKbUJAlgJhferxA4mwJPIjI3AvHEX
  template:
    metadata:
      creationTimestamp: null
      name: github-access-token
      namespace: argo

