apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: https://github.com/CuriBio/k8s_curi.git
    targetRevision: HEAD
    path: cluster/manifests/applications/overlays/test
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
