apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: pulse3d
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::245339368379:role/pulse3d-pods-iam-role01
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: apiv2
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::245339368379:role/apiv2-pods-iam-role01
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  namespace: argo
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::245339368379:role/workflow-pods-iam-role01
