apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: pulse3d
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::245339368379:role/prod-v2-pulse3d-pods-iam-role01
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: apiv2
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::245339368379:role/prod-v2-apiv2-pods-iam-role01
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  namespace: argo
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::245339368379:role/prod-v2-workflow-pods-iam-role01
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: kopf
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::245339368379:role/prod-v2-operators-iam-role01

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: argocd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::245339368379:role/prod-v2-loki-pods-iam-role01
