apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: pulse3d
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::725604423866:role/pulse3d-pods-iam-role01
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: apiv2
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::725604423866:role/apiv2-pods-iam-role01
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  namespace: argo
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::725604423866:role/workflow-pods-iam-role01
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-sa-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: argo
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sa-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: argo-workflows-sa
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: default-argo-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: kopf
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::725604423866:role/operators-iam-role01

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: argocd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::725604423866:role/loki-pods-iam-role01
