apiVersion: batch/v1
kind: Job
metadata:
  name: pheno-worker
spec:
  template:
    spec:
      containers:
        - name: pheno-worker
          image: 077346344852.dkr.ecr.us-east-2.amazonaws.com/pheno-worker
          env:
            - name: DB_NAME
              value: 'test'
            - name: HOST
              value: 'test'
            - name: USER
              value: 'test'
            - name: PASSWORD
              value: 'test'
            - name: PORT
              value: '8000'
      restartPolicy: Never
  backoffLimit: 4
