apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: postgresql-scaledobject
  namespace: pulse3d
spec:
  jobTargetRef:
    template:
      ttlSecondsAfterFinished: 0
      spec:
        containers:
          - name: pulse3d-worker
            image: 077346344852.dkr.ecr.us-east-2.amazonaws.com/pulse3d-worker
            env:
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: curibio-jobs-creds
                    key: curibio_jobs
              - name: UPLOADS_BUCKET_ENV
                value: curi-test-upload
              - name: LOGS_BUCKET_ENV
                value: test-mantarray-logs
        restartPolicy: Never
    backoffLimit: 4
  pollingInterval: 30
  triggers:
    - type: postgresql
      metadata:
        userName: 'curibio_jobs'
        host: psql-rds.default
        port: '5432'
        dbName: curibio
        sslmode: disable
        passwordFromEnv: POSTGRES_PASSWORD
        query: 'SELECT ceil(COUNT(*)::decimal / 4) FROM (SELECT id FROM jobs_queue FOR UPDATE SKIP LOCKED) q'
        targetQueryValue: '1'
