apiVersion: v1
kind: Service
metadata:
  name: psql-rds
  namespace: default
spec:
  externalName: prod-curibio.cluster-ceyftucdpgdc.us-east-2.rds.amazonaws.com
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: psql-rds
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}
