apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    path: cluster/manifests/ci/overlays/base
    repoURL: https://github.com/CuriBio/k8s_curi.git
    targetRevision: RC-07-06-23
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
