apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - argo-workflows.yaml
  - argo-events.yaml
  - ci.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/source/targetRevision
        value: modl-qc
    target:
      kind: Application
      name: argo-cd
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/source/targetRevision
        value: modl-qc
    target:
      kind: Application
      name: sealed-secrets
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/sources/0/targetRevision
        value: modl-qc
    target:
      kind: Application
      name: grafana
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/sources/1/helm/valueFiles/0
        value: $values/cluster/manifests/grafana-loki/overlays/modl/values.yaml
      - op: replace
        path: /spec/sources/0/targetRevision
        value: modl-qc
    target:
      kind: Application
      name: grafana-loki
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: cluster/manifests/autoscaler/overlays/modl
      - op: replace
        path: /spec/source/targetRevision
        value: modl-qc
    target:
      kind: Application
      name: cluster-autoscaler
      namespace: kube-system
