apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/login-attempts.json
      - dashboards/login-attempts-2.json
generatorOptions:
  disableNameSuffixHash: true
