bucket               = "curi-eks-prod-cluster-tf-state"
key                  = "prod/example/services/test.tfstate"
region               = "us-east-2"
dynamodb_table       = ""
workspace_key_prefix = "env"
